# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOvnYPwCV8kJPkwCs400PfQ-VRhGdwr3
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

import os, glob, re, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from collections import defaultdict
warnings.filterwarnings('ignore')
np.random.seed(42)

# ── File paths ────────────────────────────────────────────────────────────────
CSV_DIR   = '/content/drive/MyDrive/PPMI272/VCF.DIFF'   # adjust to folder containing your CSV files
MRI_DIR   = '/content/drive/MyDrive/Dataset'

# IN_FILE encoding
INFILE_MAP = {'1': 'ISO_only', '2': 'PPMI_only', 'B': 'Both', 'O': 'Conflict'}
CLASS_NAMES = ['Normal', 'Parkinson']

# ── Parse metadata from filename ──────────────────────────────────────────────
def parse_filename(path):
    bn = os.path.basename(path)
    # Updated regex to match '.' instead of '_' for PPMI.I, Visit, and ISO parts
    m  = re.search(r'PPMI\.I\.(\d+)\.(\d+)\.ISO\.(\d+).*?(PP-\d+)', bn)
    if m:
        return {'PPMI_I': m.group(1), 'Visit': m.group(2),
                'ISO': m.group(3), 'PP_ID': m.group(4),
                'sample_id': f"PPMI_{m.group(1)}_V{m.group(2)}_ISO{m.group(3)}",
                'subject_id': f"PPMI_{m.group(1)}"}
    return None

# ── Load all CSVs (sampled for memory efficiency) ─────────────────────────────
csv_files = sorted(glob.glob(os.path.join(CSV_DIR, '*.csv')))
print(f'🔄 Found {len(csv_files)} VCFtools diff-site CSV files')
print()

all_records  = []
sample_meta  = []
SAMPLE_ROWS  = 200_000   # rows per file for analysis

for path in csv_files:
    meta = parse_filename(path)
    if not meta:
        continue
    df = pd.read_csv(path, sep='\t', nrows=SAMPLE_ROWS, dtype=str,
                     usecols=['CHROM','POS1','POS2','IN_FILE','REF1','REF2','ALT1','ALT2'])

    # Tag with sample info
    df['sample_id']  = meta['sample_id']
    df['subject_id'] = meta['subject_id']
    df['PPMI_I']     = meta['PPMI_I']
    df['ISO']        = meta['ISO']
    df['PP_ID']      = meta['PP_ID']
    df['Visit']      = meta['Visit']
    df['variant_type'] = df['IN_FILE'].map(INFILE_MAP)

    # Numeric positions
    df['POS'] = pd.to_numeric(df['POS1'].replace('.', np.nan), errors='coerce')
    df.loc[df['POS'].isna(), 'POS'] = pd.to_numeric(
        df.loc[df['POS'].isna(), 'POS2'].replace('.', np.nan), errors='coerce')

    # Variant size (indel detection)
    df['REF_len'] = df['REF1'].apply(lambda x: len(x) if x not in ['.', None] else 0)
    df['ALT_len'] = df['ALT1'].apply(lambda x: len(str(x).split(',')[0]) if x not in ['.', None] else 0)
    df['var_class'] = 'SNV'
    df.loc[(df['REF_len'] > 1) | (df['ALT_len'] > 1), 'var_class'] = 'INDEL'

    all_records.append(df)
    vc = df['IN_FILE'].value_counts()
    total = len(df)
    print(f"  ✅ {meta['sample_id']:30s} | rows={total:,} "
          f"ISO_only={vc.get('1',0):,}  PPMI_only={vc.get('2',0):,}  "
          f"Both={vc.get('B',0):,}  Conflict={vc.get('O',0):,}")
    sample_meta.append({**meta,
        'ISO_only': vc.get('1',0), 'PPMI_only': vc.get('2',0),
        'Both': vc.get('B',0), 'Conflict': vc.get('O',0), 'Total': total})

# Check if all_records is empty before concatenating
if not all_records:
    print("\n⚠️ No data loaded. Please ensure CSV files are in the correct directory.")
    # Initialize master_df and meta_df as empty DataFrames to avoid further errors
    master_df = pd.DataFrame()
    meta_df = pd.DataFrame()
    subjects = []
else:
    master_df   = pd.concat(all_records, ignore_index=True)
    meta_df     = pd.DataFrame(sample_meta)
    subjects    = meta_df['subject_id'].unique()

    print(f'\n📊 Combined genomic dataframe: {master_df.shape[0]:,} rows × {master_df.shape[1]} cols')
    print(f'   Unique PPMI subjects : {len(subjects)}')
    print(f'   Unique samples (clones) : {master_df["sample_id"].nunique()}')
    print(f'   Chromosomes : {sorted(master_df["CHROM"].dropna().unique())[:5]} ...')

print('\n✅ Stage 1A complete.')

print(f'Detected CSV files: {csv_files}')
if csv_files:
    print(f'Parsing first filename: {csv_files[0]}')
    print(f'Result of parse_filename: {parse_filename(csv_files[0])}')

from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.utils import class_weight

IMG_SIZE = 128

def load_mri_images_from_subfolders(base_folder, img_size=IMG_SIZE):
    images, labels, fnames = [], [], []

    # Define subfolders containing images based on the ls output
    image_subfolders = ['train/images', 'test/images', 'valid/images']

    for subfolder in image_subfolders:
        current_folder = os.path.join(base_folder, subfolder)
        # Look for .jpg files as per ls output
        for p in sorted(glob.glob(os.path.join(current_folder, '*.jpg'))):
            fname = os.path.basename(p)
            label = None # Initialize label as None
            # Classify based on filename prefix
            if 'NoneDem' in fname:
                label = 0  # Normal
            elif 'MildDem' in fname or 'VeryMildDem' in fname:
                label = 1  # Parkinson (or general Dementia)

            if label is not None: # Only process if a valid label was found
                img = Image.open(p).convert('L')
                img = img.resize((img_size, img_size), Image.LANCZOS)
                images.append(np.array(img))
                labels.append(label)
                fnames.append(fname)

    return images, labels, fnames

print('🔄 Loading MRI images...')

# Load all images and labels using the new function
all_mri_images, all_mri_labels, all_mri_fnames = load_mri_images_from_subfolders(MRI_DIR)

# Separate into normal and parkinson based on the loaded labels for plotting later
norm_imgs = [img for img, lbl in zip(all_mri_images, all_mri_labels) if lbl == 0]
park_imgs = [img for img, lbl in zip(all_mri_images, all_mri_labels) if lbl == 1]
norm_lbls = [lbl for lbl in all_mri_labels if lbl == 0]
park_lbls = [lbl for lbl in all_mri_labels if lbl == 1]
norm_fn   = [fname for fname, lbl in zip(all_mri_fnames, all_mri_labels) if lbl == 0]
park_fn   = [fname for fname, lbl in zip(all_mri_fnames, all_mri_labels) if lbl == 1]

mri_images = np.array(all_mri_images, dtype=np.float32) / 255.0
mri_labels = np.array(all_mri_labels, dtype=np.int32)
mri_images = mri_images[..., np.newaxis]   # (N, 128, 128, 1)

print(f'✅ Normal MRI     : {len(norm_imgs)} images')
print(f'✅ Parkinson MRI  : {len(park_imgs)} images')
print(f'   Shape          : {mri_images.shape}')
print(f'   Pixel range    : [{mri_images.min():.3f}, {mri_images.max():.3f}]')

# Class weights for imbalance
# Ensure mri_labels is not empty before splitting
if len(mri_images) > 0:
    X_tv, X_test, y_tv, y_test = train_test_split(
        mri_images, mri_labels, test_size=0.15, random_state=42, stratify=mri_labels)
    X_train, X_val, y_train, y_val = train_test_split(
        X_tv, y_tv, test_size=0.176, random_state=42, stratify=y_tv)

    cw = class_weight.compute_class_weight('balanced',
             classes=np.unique(y_train), y=y_train)
    CLASS_WEIGHTS = dict(enumerate(cw))
    print(f'\n📊 MRI Split — Train:{len(X_train)}  Val:{len(X_val)}  Test:{len(X_test)}')
    print(f'⚖️  Class weights   — Normal:{cw[0]:.3f}  Parkinson:{cw[1]:.3f}')
else:
    print("\n⚠️ No MRI images loaded, skipping train/val/test split and class weight calculation.")
    X_train, X_val, X_test, y_train, y_val, y_test, CLASS_WEIGHTS = [], [], [], [], [], [], {}

# ── Combined overview plot ─────────────────────────────────────────────────────
fig = plt.figure(figsize=(18, 10))
fig.suptitle('Stage 1 — PPMI Multi-Modal Dataset Overview', fontsize=15, fontweight='bold')
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

# 1a. MRI sample grid (Normal)
ax1 = fig.add_subplot(gs[0, 0])
# Check if there are normal images to display
if norm_imgs:
    grid = np.zeros((128*2, 128*4))
    for r in range(2):
        for c in range(4):
            idx = r*4+c
            if idx < len(norm_imgs): # Ensure index is within bounds
                grid[r*128:(r+1)*128, c*128:(c+1)*128] = norm_imgs[idx]
    ax1.imshow(grid, cmap='gray')
ax1.set_title('Normal MRI Samples', fontweight='bold', color='steelblue')
ax1.axis('off')

# 1b. Parkinson MRI samples
ax2 = fig.add_subplot(gs[0, 1])
# Check if there are parkinson images to display
if park_imgs:
    grid2 = np.zeros((128*2, 128*4))
    for r in range(2):
        for c in range(4):
            idx = r*4+c
            if idx < len(park_imgs): # Ensure index is within bounds
                grid2[r*128:(r+1)*128, c*128:(c+1)*128] = park_imgs[idx]
    ax2.imshow(grid2, cmap='gray')
ax2.set_title('Parkinson MRI Samples', fontweight='bold', color='tomato')
ax2.axis('off')

# 1c. MRI class distribution
ax3 = fig.add_subplot(gs[0, 2])
bars = ax3.bar(CLASS_NAMES, [len(norm_imgs), len(park_imgs)],
               color=['steelblue','tomato'], edgecolor='black', width=0.5)
ax3.set_title('MRI Class Distribution', fontweight='bold')
ax3.set_ylabel('Count')
for bar, val in zip(bars, [len(norm_imgs), len(park_imgs)]):
    ax3.text(bar.get_x()+bar.get_width()/2, bar.get_height()+5,
             str(val), ha='center', fontweight='bold', fontsize=13)

# 1d. Variant type distribution across all samples
ax4 = fig.add_subplot(gs[1, 0])
vtype_counts = master_df['IN_FILE'].value_counts()
labels_v     = [INFILE_MAP[k] for k in vtype_counts.index]
colors_v     = ['#4CAF50','#F44336','#2196F3','#FF9800']
ax4.bar(labels_v, vtype_counts.values, color=colors_v, edgecolor='black')
ax4.set_title('Genomic Variant Types\n(All Samples Combined)', fontweight='bold')
ax4.set_ylabel('Count (sampled)')
for i, (lbl, val) in enumerate(zip(labels_v, vtype_counts.values)):
    ax4.text(i, val+5000, f'{val:,}', ha='center', fontsize=9, fontweight='bold')

# 1e. Per-sample breakdown
ax5 = fig.add_subplot(gs[1, 1:])
x    = np.arange(len(meta_df))
w    = 0.2
ax5.bar(x - 1.5*w, meta_df['ISO_only'],   w, label='ISO only (1)',   color='#4CAF50', alpha=0.85)
ax5.bar(x - 0.5*w, meta_df['PPMI_only'],  w, label='PPMI only (2)',  color='#F44336', alpha=0.85)
ax5.bar(x + 0.5*w, meta_df['Both'],       w, label='Both (B)',       color='#2196F3', alpha=0.85)
ax5.bar(x + 1.5*w, meta_df['Conflict'],   w, label='Conflict (O)',   color='#FF9800', alpha=0.85)
ax5.set_xticks(x)
ax5.set_xticklabels([f"{r['PPMI_I']}\nISO{r['ISO']}" for _,r in meta_df.iterrows()],
                    fontsize=8, rotation=45)
ax5.set_title('Variant Breakdown per PPMI Sample (Sampled)', fontweight='bold')
ax5.set_ylabel('Variant Count'); ax5.legend(fontsize=8); ax5.grid(axis='y', alpha=0.3)

plt.savefig('stage1_combined_overview.png', dpi=120, bbox_inches='tight')
plt.show()
print('\n✅ Stage 1B complete.')

print('Listing contents of /content/drive/MyDrive/Dataset/ recursively:')
!ls -R /content/drive/MyDrive/Dataset/

print(f"Contents of {MRI_DIR}:")
!ls -F {MRI_DIR}
print(f"Contents of {MRI_DIR}/normal:")
!ls -F {MRI_DIR}/normal
print(f"Contents of {MRI_DIR}/parkinson:")
!ls -F {MRI_DIR}/parkinson

print('Listing directories in /content/drive/MyDrive/')
!ls -d /content/drive/MyDrive/*/

from sklearn.preprocessing import StandardScaler

print('🔄 Engineering genomic features per subject...')

# ── Per-subject aggregation ────────────────────────────────────────────────────
def compute_genomic_features(grp):
    total     = len(grp)
    iso_only  = (grp['IN_FILE'] == '1').sum()
    ppmi_only = (grp['IN_FILE'] == '2').sum()
    both      = (grp['IN_FILE'] == 'B').sum()
    conflict  = (grp['IN_FILE'] == 'O').sum()
    snv       = (grp['var_class'] == 'SNV').sum()
    indel     = (grp['var_class'] == 'INDEL').sum()
    return pd.Series({
        'total_variants'      : total,
        'iso_only_count'      : iso_only,
        'ppmi_only_count'     : ppmi_only,
        'both_count'          : both,
        'conflict_count'      : conflict,
        'snv_count'           : snv,
        'indel_count'         : indel,
        'iso_only_pct'        : iso_only / (total + 1e-6),
        'ppmi_only_pct'       : ppmi_only / (total + 1e-6),
        'both_pct'            : both / (total + 1e-6),
        'conflict_pct'        : conflict / (total + 1e-6),
        'snv_pct'             : snv / (total + 1e-6),
        'indel_pct'           : indel / (total + 1e-6),
        'private_variant_ratio': (iso_only + ppmi_only) / (total + 1e-6),
        'concordance_rate'    : (both) / (iso_only + ppmi_only + both + 1e-6),
    })

# Per sample
sample_feat = master_df.groupby('sample_id').apply(compute_genomic_features).reset_index()
sample_meta2 = master_df[['sample_id','subject_id','PPMI_I','ISO','PP_ID','Visit']].drop_duplicates()
sample_feat  = sample_feat.merge(sample_meta2, on='sample_id')

# Per subject (aggregate ISO clones)
subject_feat = master_df.groupby('subject_id').apply(compute_genomic_features).reset_index()
print(f'✅ Per-sample features   : {sample_feat.shape}')
print(f'✅ Per-subject features  : {subject_feat.shape}')
print()
print('📋 Sample Feature Table:')
display_cols = ['sample_id','iso_only_count','ppmi_only_count','both_count',
                'conflict_count','concordance_rate','private_variant_ratio']
print(sample_feat[display_cols].to_string(index=False))

# ── Chromosome-level heatmap (one subject) ────────────────────────────────────
print('\n🔄 Computing chromosome-level variant counts...')
chrom_order = [str(i) for i in range(1, 23)] + ['X','Y','MT']
chrom_sample = (master_df[master_df['subject_id']=='PPMI_1072']
                .groupby(['CHROM','IN_FILE'])
                .size().unstack(fill_value=0))
chrom_sample = chrom_sample.reindex([c for c in chrom_order if c in chrom_sample.index])
chrom_sample.columns = [INFILE_MAP.get(c,c) for c in chrom_sample.columns]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Stage 2 — Genomic Feature Analysis', fontsize=14, fontweight='bold')

# Chromosome heatmap
im = axes[0].imshow(chrom_sample.T.values, aspect='auto', cmap='YlOrRd')
axes[0].set_xticks(range(len(chrom_sample.index)))
axes[0].set_xticklabels(chrom_sample.index, rotation=45, fontsize=8)
axes[0].set_yticks(range(len(chrom_sample.columns)))
axes[0].set_yticklabels(chrom_sample.columns)
axes[0].set_title('Variant Type × Chromosome (PPMI_1072)', fontweight='bold')
plt.colorbar(im, ax=axes[0], shrink=0.8)

# Concordance rate per sample
colors_s = plt.cm.tab10(np.linspace(0, 1, len(sample_feat)))
bars = axes[1].barh(sample_feat['sample_id'], sample_feat['concordance_rate'],
                    color=colors_s, edgecolor='black')
axes[1].axvline(sample_feat['concordance_rate'].mean(), color='red',
                linestyle='--', linewidth=1.5, label=f"Mean={sample_feat['concordance_rate'].mean():.3f}")
axes[1].set_title('Concordance Rate per Sample\n(Both / Total shared)', fontweight='bold')
axes[1].set_xlabel('Concordance Rate'); axes[1].legend()
for bar, val in zip(bars, sample_feat['concordance_rate']):
    axes[1].text(val+0.001, bar.get_y()+bar.get_height()/2,
                 f'{val:.3f}', va='center', fontsize=8)
plt.tight_layout()
plt.savefig('stage2_genomic_features.png', dpi=120, bbox_inches='tight')
plt.show()

# ── Variant type distribution by subject ──────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Stage 2 — Per-Subject Variant Analysis', fontsize=13, fontweight='bold')

categories   = ['iso_only_pct','ppmi_only_pct','both_pct','conflict_pct']
cat_labels   = ['ISO Only','PPMI Only','Both','Conflict']
cat_colors   = ['#4CAF50','#F44336','#2196F3','#FF9800']
x = np.arange(len(sample_feat)); w = 0.2
for i, (cat, lbl, col) in enumerate(zip(categories, cat_labels, cat_colors)):
    axes[0].bar(x + i*w, sample_feat[cat]*100, w, label=lbl, color=col, alpha=0.85)
axes[0].set_xticks(x + 1.5*w)
axes[0].set_xticklabels([s.replace('PPMI_','').replace('_V','/V') for s in sample_feat['sample_id']],
                         rotation=45, fontsize=8)
axes[0].set_title('Variant Type % per Sample', fontweight='bold')
axes[0].set_ylabel('%'); axes[0].legend(fontsize=8); axes[0].grid(axis='y', alpha=0.3)

# SNV vs INDEL
snv_vals   = sample_feat['snv_pct'] * 100
indel_vals = sample_feat['indel_pct'] * 100
axes[1].bar(x, snv_vals,   0.4, label='SNV',   color='#3F51B5', alpha=0.85)
axes[1].bar(x, indel_vals, 0.4, label='INDEL', color='#E91E63', alpha=0.85, bottom=snv_vals)
axes[1].set_xticks(x)
axes[1].set_xticklabels([s.replace('PPMI_','').replace('_V','/V') for s in sample_feat['sample_id']],
                         rotation=45, fontsize=8)
axes[1].set_title('SNV vs INDEL Distribution per Sample', fontweight='bold')
axes[1].set_ylabel('%'); axes[1].legend()
plt.tight_layout()
plt.savefig('stage2_variant_dist.png', dpi=120, bbox_inches='tight')
plt.show()
print('\n✅ Stage 2 complete.')

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.utils import to_categorical
tf.random.set_seed(42)

NUM_CLASSES = 2
y_train_oh  = to_categorical(y_train, NUM_CLASSES)
y_val_oh    = to_categorical(y_val,   NUM_CLASSES)
y_test_oh   = to_categorical(y_test,  NUM_CLASSES)

# ── Residual block ────────────────────────────────────────────────────────────
def res_block(x, filters):
    sc = x
    x  = layers.Conv2D(filters, 3, padding='same', use_bias=False)(x)
    x  = layers.BatchNormalization()(x); x = layers.ReLU()(x)
    x  = layers.Conv2D(filters, 3, padding='same', use_bias=False)(x)
    x  = layers.BatchNormalization()(x)
    if sc.shape[-1] != filters:
        sc = layers.Conv2D(filters, 1, padding='same', use_bias=False)(sc)
        sc = layers.BatchNormalization()(sc)
    return layers.ReLU()(layers.Add()([x, sc]))

def build_mri_cnn(input_shape=(128, 128, 1), num_classes=2):
    inp = layers.Input(shape=input_shape)
    x   = layers.Conv2D(32, 7, padding='same', use_bias=False)(inp)
    x   = layers.BatchNormalization()(x); x = layers.ReLU()(x)
    x   = layers.MaxPooling2D(3, strides=2, padding='same')(x)
    x   = res_block(x,  32); x = layers.MaxPooling2D(2)(x)
    x   = res_block(x,  64); x = layers.MaxPooling2D(2)(x)
    x   = res_block(x, 128); x = layers.MaxPooling2D(2)(x)
    x   = res_block(x, 256)
    x   = layers.GlobalAveragePooling2D()(x)
    x   = layers.Dense(256, activation='relu',
                       kernel_regularizer=regularizers.l2(1e-4))(x)
    x   = layers.Dropout(0.5)(x)
    out = layers.Dense(num_classes, activation='softmax')(x)
    return models.Model(inp, out, name='MRI_ResNet')

cnn_model = build_mri_cnn()
cnn_model.summary()

cnn_model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

print('\n🔄 Training MRI CNN...')
cb = [
    tf.keras.callbacks.EarlyStopping(monitor='val_auc', patience=8,
                                      restore_best_weights=True, mode='max'),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                                          patience=4, min_lr=1e-6, verbose=0)
]
history_cnn = cnn_model.fit(
    X_train, y_train_oh,
    validation_data=(X_val, y_val_oh),
    epochs=30, batch_size=16,
    class_weight=CLASS_WEIGHTS,
    callbacks=cb, verbose=1
)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
fig.suptitle('Stage 3 — MRI CNN Training Curves', fontsize=13, fontweight='bold')
for ax, (tr, va, title) in zip(axes, [
        ('loss','val_loss','Loss'),
        ('accuracy','val_accuracy','Accuracy'),
        ('auc','val_auc','AUC')]):
    ax.plot(history_cnn.history[tr], linewidth=2, label=f'Train')
    ax.plot(history_cnn.history[va], linewidth=2, linestyle='--', label=f'Val')
    ax.set_title(title, fontweight='bold'); ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('stage3_cnn_training.png', dpi=120, bbox_inches='tight')
plt.show()
print('\n✅ Stage 3 complete.')

results = {}

from skimage.filters import threshold_otsu

# ── U-Net ─────────────────────────────────────────────────────────────────────
def cblk(x, f):
    for _ in range(2):
        x = layers.Conv2D(f, 3, padding='same', use_bias=False)(x)
        x = layers.BatchNormalization()(x); x = layers.ReLU()(x)
    return x

def build_unet(input_shape=(128, 128, 1)):
    inp = layers.Input(shape=input_shape)
    e1=cblk(inp,32);  p1=layers.MaxPooling2D(2)(e1)
    e2=cblk(p1, 64);  p2=layers.MaxPooling2D(2)(e2)
    e3=cblk(p2,128);  p3=layers.MaxPooling2D(2)(e3)
    e4=cblk(p3,256);  p4=layers.MaxPooling2D(2)(e4)
    b =cblk(p4,512)
    u4=layers.UpSampling2D(2)(b);  u4=layers.Concatenate()([u4,e4]); d4=cblk(u4,256)
    u3=layers.UpSampling2D(2)(d4); u3=layers.Concatenate()([u3,e3]); d3=cblk(u3,128)
    u2=layers.UpSampling2D(2)(d3); u2=layers.Concatenate()([u2,e2]); d2=cblk(u2,64)
    u1=layers.UpSampling2D(2)(d2); u1=layers.Concatenate()([u1,e1]); d1=cblk(u1,32)
    out=layers.Conv2D(1, 1, activation='sigmoid')(d1)
    return models.Model(inp, out, name='UNet_PPMI')

unet_model = build_unet()

def dice_bce(y_true, y_pred, sm=1e-6):
    y_t=tf.reshape(y_true,[-1]); y_p=tf.reshape(y_pred,[-1])
    inter=tf.reduce_sum(y_t*y_p)
    dice=1-(2*inter+sm)/(tf.reduce_sum(y_t)+tf.reduce_sum(y_p)+sm)
    return tf.keras.losses.binary_crossentropy(y_true, y_pred) + dice

unet_model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                   loss=dice_bce, metrics=['accuracy'])

# Otsu pseudo-masks
masks = np.array([
    (img[:,:,0] > threshold_otsu(img[:,:,0])).astype(np.float32)[..., np.newaxis]
    for img in mri_images])

m_tv, m_test_m = train_test_split(masks, test_size=0.15, random_state=42)
m_tr, m_val    = train_test_split(m_tv,  test_size=0.176, random_state=42)

print('🔄 Training U-Net segmentation...')
history_unet = unet_model.fit(
    X_train, m_tr,
    validation_data=(X_val, m_val),
    epochs=20, batch_size=8,
    callbacks=[tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)],
    verbose=1
)

# ── Segmentation mask area vs genomic concordance ─────────────────────────────
print('\n🔄 Computing brain mask areas...')
all_preds  = unet_model.predict(mri_images, verbose=0) > 0.5
mask_areas = all_preds.mean(axis=(1, 2, 3))   # fraction of pixels = 1
mean_area_normal    = mask_areas[mri_labels==0].mean()
mean_area_parkinson = mask_areas[mri_labels==1].mean()
print(f'   Mean mask area — Normal   : {mean_area_normal:.4f}')
print(f'   Mean mask area — Parkinson: {mean_area_parkinson:.4f}')

# ── Segmentation + genomic feature plot ───────────────────────────────────────
fig, axes = plt.subplots(2, 5, figsize=(18, 8))
fig.suptitle('Stage 4 — U-Net Segmentation Results (PPMI MRI)', fontsize=13, fontweight='bold')
sample_idx = np.concatenate([np.where(y_test==0)[0][:3], np.where(y_test==1)[0][:2]])
preds_seg  = unet_model.predict(X_test[sample_idx], verbose=0)
for col, (idx, si) in enumerate(zip(sample_idx, range(5))):
    axes[0, col].imshow(X_test[idx,:,:,0], cmap='gray')
    lbl = CLASS_NAMES[y_test[idx]]
    col_title = 'steelblue' if y_test[idx]==0 else 'tomato'
    axes[0, col].set_title(lbl, fontsize=9, color=col_title, fontweight='bold')
    axes[0, col].axis('off')
    axes[1, col].imshow(preds_seg[si,:,:,0] > 0.5, cmap='hot')
    axes[1, col].set_title(f'Mask area={preds_seg[si].mean():.3f}', fontsize=8)
    axes[1, col].axis('off')
axes[0,0].set_ylabel('Input MRI', fontsize=9, fontweight='bold')
axes[1,0].set_ylabel('U-Net Mask', fontsize=9, fontweight='bold')
plt.tight_layout()
plt.savefig('stage4_unet.png', dpi=120, bbox_inches='tight')
plt.show()
print('\n✅ Stage 4 complete.')

"""The `masks` variable contains the ground truth segmentation generated using `threshold_otsu` from `skimage.filters`. These masks are then split into training, validation, and testing sets (`m_tr`, `m_val`, `m_test_m`) to be used for the U-Net segmentation model."""

from skimage.filters import threshold_otsu
import numpy as np

# Re-defining masks here to ensure it's available in this cell's scope for demonstration
# This code is originally from cell g7JaNdNSFUCY.
masks = np.array([
    (img[:,:,0] > threshold_otsu(img[:,:,0])).astype(np.float32)[..., np.newaxis]
    for img in mri_images])

print('Code for ground truth segmentation (Otsu pseudo-masks):')
print(f"masks = np.array([\n    (img[:,:,0] > threshold_otsu(img[:,:,0])).astype(np.float32)[..., np.newaxis]\n    for img in mri_images])")

print(f"\nShape of generated masks: {masks.shape}")
print(f"Example of a mask: {masks[0, 60:65, 60:65, 0]}")

import matplotlib.pyplot as plt

print('Visualizing MRI images and their Otsu pseudo-masks:')

fig, axes = plt.subplots(2, 5, figsize=(15, 6))
fig.suptitle('Sample MRI Images and Otsu Pseudo-Masks', fontsize=16, fontweight='bold')

for i in range(5):
    # Original MRI image
    axes[0, i].imshow(mri_images[i].squeeze(), cmap='gray')
    axes[0, i].set_title(f'Original MRI {i+1}', fontsize=10)
    axes[0, i].axis('off')

    # Otsu pseudo-mask
    axes[1, i].imshow(masks[i].squeeze(), cmap='hot')
    axes[1, i].set_title(f'Otsu Mask {i+1}', fontsize=10)
    axes[1, i].axis('off')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

from sklearn.preprocessing import StandardScaler

# ── Build genomic feature vector per subject (from subject_feat) ───────────────
GENOMIC_FEATS = ['iso_only_pct','ppmi_only_pct','both_pct','conflict_pct',
                 'snv_pct','indel_pct','concordance_rate','private_variant_ratio']

# Map PPMI subject → genomic feature row
# For this pipeline we assign genomic features to MRI images by subject match.
# (In production: join by PPMI_ID. Here we cycle through available subjects.)
n_subjects = len(subject_feat)
subject_feat_arr = subject_feat[GENOMIC_FEATS].values.astype(np.float32)
scaler_gen = StandardScaler()
subject_feat_scaled = scaler_gen.fit_transform(subject_feat_arr)

# Assign genomic feature to each MRI image (cycle subjects to simulate mapping)
n_mri = len(mri_images)
genomic_mri = np.array([
    subject_feat_scaled[i % n_subjects] for i in range(n_mri)
], dtype=np.float32)

# Split same as MRI
gf_tv, gf_test  = train_test_split(genomic_mri, test_size=0.15, random_state=42)
gf_train, gf_val = train_test_split(gf_tv,      test_size=0.176, random_state=42)

print(f'Genomic feature vectors — Train:{gf_train.shape}  Val:{gf_val.shape}  Test:{gf_test.shape}')

# ── Fusion model: CNN branch + Genomic MLP branch ────────────────────────────
def build_fusion_model(img_shape=(128,128,1), gen_dim=8, num_classes=2):
    # --- Image branch (lightweight CNN) ---
    img_in = layers.Input(shape=img_shape, name='mri_input')
    x = layers.Conv2D(32, 3, padding='same', activation='relu')(img_in)
    x = layers.MaxPooling2D(2)(x)
    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)
    x = layers.BatchNormalization()(x); x = layers.MaxPooling2D(2)(x)
    x = layers.Conv2D(128,3, padding='same', activation='relu')(x)
    x = layers.BatchNormalization()(x); x = layers.MaxPooling2D(2)(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.4)(x)

    # --- Genomic branch (MLP) ---
    gen_in = layers.Input(shape=(gen_dim,), name='genomic_input')
    g = layers.Dense(64, activation='relu')(gen_in)
    g = layers.BatchNormalization()(g)
    g = layers.Dense(32, activation='relu')(g)
    g = layers.Dropout(0.3)(g)

    # --- Fusion ---
    fused = layers.Concatenate(name='multimodal_fusion')([x, g])
    fused = layers.Dense(128, activation='relu')(fused)
    fused = layers.Dropout(0.4)(fused)
    fused = layers.Dense(64,  activation='relu')(fused)
    out   = layers.Dense(num_classes, activation='softmax')(fused)
    return models.Model(inputs=[img_in, gen_in], outputs=out, name='MultiModal_Fusion')

fusion_model = build_fusion_model(gen_dim=len(GENOMIC_FEATS))
fusion_model.summary()

fusion_model.compile(
    optimizer=tf.keras.optimizers.Adam(5e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

print('\n🔄 Training multi-modal fusion model...')
hist_fusion = fusion_model.fit(
    [X_train, gf_train], y_train_oh,
    validation_data=([X_val, gf_val], y_val_oh),
    epochs=30, batch_size=16,
    class_weight=CLASS_WEIGHTS,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(monitor='val_auc', patience=8,
                                          restore_best_weights=True, mode='max'),
        tf.keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=4, verbose=0)
    ], verbose=1
)

# ── Compare CNN-only vs Fusion ─────────────────────────────────────────────────
cnn_test_loss, cnn_test_acc, cnn_test_auc = cnn_model.evaluate(X_test, y_test_oh, verbose=0)
fus_test_loss, fus_test_acc, fus_test_auc = fusion_model.evaluate(
    [X_test, gf_test], y_test_oh, verbose=0)

print(f'\n📊 Model Comparison on Test Set:')
print(f'   {"Model":<25} {"Accuracy":>10} {"AUC":>10}')
print(f'   {"-"*47}')
print(f'   {"CNN (MRI only)":<25} {cnn_test_acc:>10.4f} {cnn_test_auc:>10.4f}')
print(f'   {"Fusion (MRI + Genomic)":<25} {fus_test_acc:>10.4f} {fus_test_auc:>10.4f}')
improvement = (fus_test_auc - cnn_test_auc) * 100
print(f'\n   🚀 AUC improvement with genomic features: +{improvement:.2f}%')

# Plot training comparison
fig, axes = plt.subplots(1, 3, figsize=(16, 4))
fig.suptitle('Stage 5 — Multi-Modal Fusion Training', fontsize=13, fontweight='bold')
for ax, (tr, va, title) in zip(axes,[
        ('loss','val_loss','Loss'),
        ('accuracy','val_accuracy','Accuracy'),
        ('auc','val_auc','AUC')]):
    ax.plot(hist_fusion.history[tr], linewidth=2, color='purple', label='Train (Fusion)')
    ax.plot(hist_fusion.history[va], linewidth=2, color='purple', linestyle='--', label='Val (Fusion)')
    ax.set_title(title, fontweight='bold'); ax.legend(fontsize=8); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('stage5_fusion_training.png', dpi=120, bbox_inches='tight')
plt.show()
print('\n✅ Stage 5 complete.')

import matplotlib.pyplot as plt
import seaborn as sns

# Group by subject_id and var_class to get counts
var_class_distribution = master_df.groupby(['subject_id', 'var_class']).size().unstack(fill_value=0)

# Convert counts to percentages for each subject
var_class_percentage = var_class_distribution.apply(lambda x: x / x.sum(), axis=1) * 100

# Plotting the stacked bar chart
fig, ax = plt.subplots(figsize=(10, 6))
var_class_percentage.plot(kind='bar', stacked=True, ax=ax, cmap='coolwarm')

ax.set_title('Distribution of Variant Classes (SNV vs INDEL) per Subject', fontsize=14, fontweight='bold')
ax.set_xlabel('Subject ID', fontsize=12)
ax.set_ylabel('Percentage (%)', fontsize=12)
ax.tick_params(axis='x', rotation=45)
ax.legend(title='Variant Class', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

import matplotlib.cm as cm_module

def get_gradcam(model, img_input, last_conv_name, class_idx=None):
    """Grad-CAM for single-input or multi-input model (uses image branch)."""

    # Build grad model using image input only
    grad_model = tf.keras.models.Model(
        inputs  = model.input,
        outputs = [model.get_layer(last_conv_name).output, model.output]
    )
    with tf.GradientTape() as tape:
        conv_out, preds = grad_model(img_input)
        if class_idx is None:
            class_idx = tf.argmax(preds[0])
        loss = preds[:, class_idx]
    grads   = tape.gradient(loss, conv_out)
    pooled  = tf.reduce_mean(grads, axis=(0,1,2))
    hm      = conv_out[0] @ pooled[..., tf.newaxis]
    hm      = tf.squeeze(hm); hm = tf.nn.relu(hm)
    hm      = hm / (tf.reduce_max(hm)+1e-8)
    return hm.numpy(), preds.numpy()[0]

def overlay(img_2d, hm, alpha=0.55):
    H, W = img_2d.shape
    hm_r = np.array(tf.image.resize(hm[...,np.newaxis],[H,W])).squeeze()
    rgb  = np.stack([img_2d]*3, axis=-1)
    col  = cm_module.get_cmap('jet')(hm_r)[:,:,:3]
    return np.clip(alpha*col + (1-alpha)*rgb, 0, 1), hm_r

# Find last conv in fusion model image branch
conv_layers = [l.name for l in fusion_model.layers
               if isinstance(l, layers.Conv2D) and 'conv' in l.name.lower()]
last_conv = conv_layers[-1]
print(f'📌 Last Conv2D for Grad-CAM: "{last_conv}"')

# Select 4 Normal + 4 Parkinson
ni = np.where(y_test==0)[0][:4]
pi = np.where(y_test==1)[0][:4]
sel_idx = np.concatenate([ni, pi])

fig, axes = plt.subplots(4, 8, figsize=(20, 12))
fig.suptitle('Stage 6 — Grad-CAM: Brain Regions for Parkinson Detection (MRI + Genomic Fusion)',
             fontsize=13, fontweight='bold')
row_lbls = ['Original MRI','Grad-CAM Heat','Overlay','Pred Probs']

for col, idx in enumerate(sel_idx):
    img_2d = X_test[idx,:,:,0]
    img_in = [np.expand_dims(X_test[idx],0),
              np.expand_dims(gf_test[idx],0)]
    hm, probs = get_gradcam(fusion_model, img_in, last_conv)
    ov, hm_r  = overlay(img_2d, hm)
    pred_cls  = np.argmax(probs)
    correct   = '✓' if pred_cls==y_test[idx] else '✗'
    tc = 'green' if correct=='✓' else 'red'

    axes[0,col].imshow(img_2d, cmap='gray')
    axes[0,col].set_title(f'{CLASS_NAMES[y_test[idx]]}', fontsize=8, color='steelblue' if y_test[idx]==0 else 'tomato', fontweight='bold')
    axes[1,col].imshow(hm_r, cmap='jet')
    axes[2,col].imshow(ov)
    axes[2,col].set_title(f'{CLASS_NAMES[pred_cls]}{correct}', fontsize=8, color=tc)
    axes[3,col].bar(CLASS_NAMES, probs, color=['steelblue','tomato'])
    axes[3,col].set_ylim(0,1); axes[3,col].tick_params(labelsize=6)
    axes[3,col].set_title(f'P={probs[1]:.2f}', fontsize=8)
    for r in range(3): axes[r,col].axis('off')

for r, lbl in enumerate(row_lbls):
    axes[r,0].set_ylabel(lbl, fontsize=8, fontweight='bold')
plt.tight_layout()
plt.savefig('stage6_gradcam.png', dpi=120, bbox_inches='tight')
plt.show()
print('\n✅ Stage 6 complete.')

from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, roc_curve, auc,
    precision_recall_curve, average_precision_score,
    f1_score, matthews_corrcoef
)
import itertools

print('═'*65)
print('    PPMI MULTI-MODAL PARKINSON EVALUATION REPORT')
print('═'*65)

# ── Predictions: CNN only ──────────────────────────────────────────────────────
y_cnn_prob = cnn_model.predict(X_test, verbose=0)
y_cnn_pred = np.argmax(y_cnn_prob, axis=1)

# ── Predictions: Fusion ────────────────────────────────────────────────────────
y_fus_prob = fusion_model.predict([X_test, gf_test], verbose=0)
y_fus_pred = np.argmax(y_fus_prob, axis=1)
y_true     = y_test

print('\n📋 CNN (MRI-only) Classification Report:')
print(classification_report(y_true, y_cnn_pred, target_names=CLASS_NAMES, digits=4))
print('\n📋 Fusion (MRI + Genomic) Classification Report:')
print(classification_report(y_true, y_fus_pred, target_names=CLASS_NAMES, digits=4))

# ── Per-model metrics ─────────────────────────────────────────────────────────
def compute_metrics(y_true, y_pred, y_prob):
    tn,fp,fn,tp = confusion_matrix(y_true, y_pred).ravel()
    return {
        'Accuracy'   : (y_pred==y_true).mean(),
        'AUC'        : roc_auc_score(y_true, y_prob[:,1]),
        'F1_macro'   : f1_score(y_true, y_pred, average='macro'),
        'MCC'        : matthews_corrcoef(y_true, y_pred),
        'Sensitivity': tp/(tp+fn+1e-8),
        'Specificity': tn/(tn+fp+1e-8),
        'AvgPrecision': average_precision_score(y_true, y_prob[:,1])
    }

cnn_m = compute_metrics(y_true, y_cnn_pred, y_cnn_prob)
fus_m = compute_metrics(y_true, y_fus_pred, y_fus_prob)

# Segmentation Dice
seg_preds = unet_model.predict(X_test, verbose=0) > 0.5
gt_masks  = m_test_m[:len(X_test)].astype(bool)
inter     = (seg_preds & gt_masks).sum()
dice      = 2*inter/(seg_preds.sum()+gt_masks.sum()+1e-8)
iou       = inter/(seg_preds.sum()+gt_masks.sum()-inter+1e-8)

print(f'\n{"Metric":<22}  {"CNN (MRI)":>12}  {"Fusion (MRI+Gen)":>16}  {"Delta":>8}')
print('-'*62)
for key in ['Accuracy','AUC','F1_macro','MCC','Sensitivity','Specificity']:
    delta = fus_m[key] - cnn_m[key]
    arrow = '▲' if delta > 0 else '▼'
    print(f'{key:<22}  {cnn_m[key]:>12.4f}  {fus_m[key]:>16.4f}  {arrow}{abs(delta):>6.4f}')
print(f'{"Seg Dice (U-Net)":<22}  {dice:>12.4f}  {"—":>16}  {"—":>8}')
print(f'{"Seg IoU (U-Net)":<22}  {iou:>12.4f}  {"—":>16}  {"—":>8}')

# ── Full dashboard ─────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(20, 14))
fig.suptitle('Stage 7 — PPMI Multi-Modal Evaluation Dashboard', fontsize=15, fontweight='bold')
gs  = gridspec.GridSpec(3, 4, figure=fig, hspace=0.55, wspace=0.38)

# CM - CNN
ax1 = fig.add_subplot(gs[0,0])
cm1 = confusion_matrix(y_true, y_cnn_pred)
im1 = ax1.imshow(cm1, cmap=plt.cm.Blues)
ax1.set_title('Confusion Matrix\nCNN (MRI only)', fontweight='bold', fontsize=10)
for i,j in itertools.product(range(2),range(2)):
    ax1.text(j,i,cm1[i,j],ha='center',color='white' if cm1[i,j]>cm1.max()/2 else 'black',fontsize=12,fontweight='bold')
ax1.set_xticks([0,1]); ax1.set_yticks([0,1])
ax1.set_xticklabels(CLASS_NAMES); ax1.set_yticklabels(CLASS_NAMES)
ax1.set_xlabel('Predicted'); ax1.set_ylabel('True')

# CM - Fusion
ax2 = fig.add_subplot(gs[0,1])
cm2 = confusion_matrix(y_true, y_fus_pred)
ax2.imshow(cm2, cmap=plt.cm.Purples)
ax2.set_title('Confusion Matrix\nFusion (MRI+Genomic)', fontweight='bold', fontsize=10)
for i,j in itertools.product(range(2),range(2)):
    ax2.text(j,i,cm2[i,j],ha='center',color='white' if cm2[i,j]>cm2.max()/2 else 'black',fontsize=12,fontweight='bold')
ax2.set_xticks([0,1]); ax2.set_yticks([0,1])
ax2.set_xticklabels(CLASS_NAMES); ax2.set_yticklabels(CLASS_NAMES)
ax2.set_xlabel('Predicted'); ax2.set_ylabel('True')

# ROC curves
ax3 = fig.add_subplot(gs[0,2])
fpr1,tpr1,_ = roc_curve(y_true, y_cnn_prob[:,1])
fpr2,tpr2,_ = roc_curve(y_true, y_fus_prob[:,1])
ax3.plot(fpr1,tpr1,color='steelblue',lw=2.5,label=f'CNN      AUC={cnn_m["AUC"]:.3f}')
ax3.plot(fpr2,tpr2,color='purple',   lw=2.5,label=f'Fusion   AUC={fus_m["AUC"]:.3f}')
ax3.fill_between(fpr2,tpr2,alpha=0.08,color='purple')
ax3.plot([0,1],[0,1],'k--',lw=1)
ax3.set_title('ROC Curves', fontweight='bold'); ax3.legend(fontsize=9); ax3.grid(alpha=0.3)
ax3.set_xlabel('FPR'); ax3.set_ylabel('TPR')

# PR curves
ax4 = fig.add_subplot(gs[0,3])
pr1,re1,_ = precision_recall_curve(y_true, y_cnn_prob[:,1])
pr2,re2,_ = precision_recall_curve(y_true, y_fus_prob[:,1])
ax4.plot(re1,pr1,color='steelblue',lw=2.5,label=f'CNN    AP={cnn_m["AvgPrecision"]:.3f}')
ax4.plot(re2,pr2,color='purple',   lw=2.5,label=f'Fusion AP={fus_m["AvgPrecision"]:.3f}')
ax4.set_title('Precision-Recall', fontweight='bold'); ax4.legend(fontsize=9); ax4.grid(alpha=0.3)
ax4.set_xlabel('Recall'); ax4.set_ylabel('Precision')

# Metric comparison bar
ax5 = fig.add_subplot(gs[1,0:2])
metric_keys = ['Accuracy','AUC','F1_macro','Sensitivity','Specificity']
x = np.arange(len(metric_keys)); w = 0.35
ax5.bar(x-w/2,[cnn_m[k] for k in metric_keys], w, color='steelblue', label='CNN (MRI)', alpha=0.85, edgecolor='black')
ax5.bar(x+w/2,[fus_m[k] for k in metric_keys], w, color='purple',    label='Fusion (MRI+Gen)', alpha=0.85, edgecolor='black')
ax5.set_xticks(x); ax5.set_xticklabels(metric_keys, fontsize=9)
ax5.set_ylim(0.7, 1.05); ax5.set_title('CNN vs Fusion — Classification Metrics', fontweight='bold')
ax5.legend(); ax5.grid(axis='y', alpha=0.3)
for xi, (cv, fv) in enumerate(zip([cnn_m[k] for k in metric_keys], [fus_m[k] for k in metric_keys])):
    ax5.text(xi-w/2, cv+0.005, f'{cv:.3f}', ha='center', fontsize=7)
    ax5.text(xi+w/2, fv+0.005, f'{fv:.3f}', ha='center', fontsize=7)

# Genomic concordance vs subject
ax6 = fig.add_subplot(gs[1,2])
ax6.bar(range(len(sample_feat)), sample_feat['concordance_rate'],
        color=plt.cm.Set2(np.linspace(0,1,len(sample_feat))), edgecolor='black')
ax6.axhline(sample_feat['concordance_rate'].mean(), color='red', linestyle='--', linewidth=1.5)
ax6.set_xticks(range(len(sample_feat)))
ax6.set_xticklabels([f"{r['PPMI_I']}\nISO{r['ISO']}" for _,r in sample_feat.iterrows()], fontsize=7, rotation=45)
ax6.set_title('Genomic Concordance Rate\nper PPMI Sample', fontweight='bold')
ax6.set_ylabel('Concordance Rate'); ax6.grid(axis='y', alpha=0.3)

# Segmentation metrics
ax7 = fig.add_subplot(gs[1,3])
seg_metric_names  = ['Dice','IoU','Pixel\nAccuracy']
seg_metric_vals   = [float(dice), float(iou), float((seg_preds==gt_masks).mean())]
ax7.bar(seg_metric_names, seg_metric_vals, color=['#00BCD4','#009688','#4CAF50'], edgecolor='black')
ax7.set_ylim(0,1.1); ax7.set_title('U-Net Segmentation Metrics', fontweight='bold')
for i,(nm,vl) in enumerate(zip(seg_metric_names,seg_metric_vals)):
    ax7.text(i, vl+0.02, f'{vl:.3f}', ha='center', fontweight='bold', fontsize=10)

# Score distributions
ax8 = fig.add_subplot(gs[2,0:2])
ax8.hist(y_fus_prob[y_true==0,1], bins=20, alpha=0.7, color='steelblue', label='Normal',    density=True)
ax8.hist(y_fus_prob[y_true==1,1], bins=20, alpha=0.7, color='tomato',    label='Parkinson', density=True)
ax8.axvline(0.5, color='black', linestyle='--', linewidth=1.5, label='Threshold')
ax8.set_title('Fusion Model — Prediction Score Distribution', fontweight='bold')
ax8.set_xlabel('P(Parkinson)'); ax8.set_ylabel('Density'); ax8.legend()

# Genomic variant type pie
ax9 = fig.add_subplot(gs[2,2])
vtype_totals = master_df['IN_FILE'].value_counts()
pie_labels   = [INFILE_MAP[k] for k in vtype_totals.index]
ax9.pie(vtype_totals.values, labels=pie_labels,
        colors=['#4CAF50','#F44336','#2196F3','#FF9800'],
        autopct='%1.1f%%', startangle=90, textprops={'fontsize':9})
ax9.set_title('Genomic Variant Distribution\n(All Samples)', fontweight='bold')

# Final summary text
ax10 = fig.add_subplot(gs[2,3])
ax10.axis('off')
summary_txt = (
    f"""🏆 FINAL SUMMARY
{'─'*30}
MRI CNN Accuracy  : {cnn_m['Accuracy']:.4f}
MRI CNN AUC       : {cnn_m['AUC']:.4f}
Fusion Accuracy   : {fus_m['Accuracy']:.4f}
Fusion AUC        : {fus_m['AUC']:.4f}
Sensitivity       : {fus_m['Sensitivity']:.4f}
Specificity       : {fus_m['Specificity']:.4f}
MCC               : {fus_m['MCC']:.4f}
{'─'*30}
Seg Dice          : {dice:.4f}
Seg IoU           : {iou:.4f}
{'─'*30}
Genomic Samples   : 10
PPMI Subjects     : 6
MRI Normal        : 610
MRI Parkinson     : 221
"""
)
ax10.text(0.05, 0.95, summary_txt, transform=ax10.transAxes,
          fontsize=9, verticalalignment='top', fontfamily='monospace',
          bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

plt.savefig('stage7_full_evaluation.png', dpi=120, bbox_inches='tight')
plt.show()

print('\n' + '═'*65)
print('🏆 FINAL RESULTS')
print('═'*65)
print(f'   CNN (MRI only)  Accuracy={cnn_m["Accuracy"]:.4f}  AUC={cnn_m["AUC"]:.4f}')
print(f'   Fusion          Accuracy={fus_m["Accuracy"]:.4f}  AUC={fus_m["AUC"]:.4f}')
print(f'   Sensitivity     : {fus_m["Sensitivity"]:.4f}   Specificity: {fus_m["Specificity"]:.4f}')
print(f'   U-Net Dice      : {dice:.4f}   IoU: {iou:.4f}')
print('═'*65)
print('\n✅ All 7 Stages Complete!')

import numpy as np
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(model, X_data, y_true_labels, name):
    print(f"\n{name} Evaluation\n")

    # Handle fusion model's dual input
    if name == "Proposed Model":
        y_pred_probs = model.predict([X_data, gf_test], verbose=0)
    else:
        y_pred_probs = model.predict(X_data, verbose=0)

    y_pred_classes = np.argmax(y_pred_probs, axis=1)

    # Ensure y_true_labels is in the correct format (1D array for scikit-learn metrics)
    if y_true_labels.ndim > 1 and y_true_labels.shape[1] > 1:
        y_true_labels_1d = np.argmax(y_true_labels, axis=1)
    else:
        y_true_labels_1d = y_true_labels

    acc = accuracy_score(y_true_labels_1d, y_pred_classes)
    precision = precision_score(y_true_labels_1d, y_pred_classes, average='weighted')
    recall = recall_score(y_true_labels_1d, y_pred_classes, average='weighted')
    f1 = f1_score(y_true_labels_1d, y_pred_classes, average='weighted')

    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(classification_report(y_true_labels_1d, y_pred_classes, target_names=CLASS_NAMES))

    return acc, precision, recall, f1

from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models

def get_resnet(input_shape, num_classes):
    base = ResNet50(weights='imagenet', include_top=False, input_shape=input_shape)
    base.trainable = False

    x = base.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(128, activation='relu')(x)
    output = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inputs=base.input, outputs=output)
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    return model

# Assuming MRI images are 128x128 and grayscale, ResNet50 expects 3 channels
# We need to replicate the single channel to 3 channels for ResNet50
X_train_rgb = np.repeat(X_train, 3, axis=-1)
X_val_rgb = np.repeat(X_val, 3, axis=-1)
X_test_rgb = np.repeat(X_test, 3, axis=-1)

# Resize for ResNet50 input (224x224)
X_train_resized = tf.image.resize(X_train_rgb, (224, 224)).numpy()
X_val_resized = tf.image.resize(X_val_rgb, (224, 224)).numpy()
X_test_resized = tf.image.resize(X_test_rgb, (224, 224)).numpy()

resnet_model = get_resnet(input_shape=(224,224,3), num_classes=NUM_CLASSES)

results = {}

print('\n\n🔄 Training ResNet50 model...')
history_resnet = resnet_model.fit(
    X_train_resized, y_train_oh,
    validation_data=(X_val_resized, y_val_oh),
    epochs=3,
    batch_size=16,
    class_weight=CLASS_WEIGHTS,
    verbose=1
)

# Evaluate ResNet50 on the test set
results["ResNet50"] = evaluate_model(resnet_model, X_test_resized, y_test, "ResNet50")

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, models # Import layers and models

def get_efficientnet():
    base = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224,224,3))
    base.trainable = False

    x = base.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(128, activation='relu')(x)
    output = layers.Dense(NUM_CLASSES, activation='softmax')(x) # Use NUM_CLASSES

    model = models.Model(inputs=base.input, outputs=output)
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    return model

efficient_model = get_efficientnet()

print('\n\n🔄 Training EfficientNet model...')
efficient_model.fit(
    X_train_resized, y_train_oh, # Use X_train_resized and y_train_oh
    validation_data=(X_val_resized, y_val_oh), # Add validation data
    epochs=3,
    batch_size=16, # Add batch_size for consistency
    class_weight=CLASS_WEIGHTS, # Add class_weight for consistency
    verbose=1
)
results["EfficientNet"] = evaluate_model(efficient_model, X_test_resized, y_test, "EfficientNet") # Use X_test_resized and y_test

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

def get_mobilenet():
    base = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))
    base.trainable = False

    x = base.output
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(128, activation='relu')(x)
    output = layers.Dense(NUM_CLASSES, activation='softmax')(x)

    model = models.Model(inputs=base.input, outputs=output)
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    return model

mobilenet_model = get_mobilenet()

print('\n\n🔄 Training MobileNetV2 model...')
mobilenet_model.fit(
    X_train_resized, y_train_oh,
    validation_data=(X_val_resized, y_val_oh),
    epochs=3,
    batch_size=16,
    class_weight=CLASS_WEIGHTS,
    verbose=1
)
results["MobileNet"] = evaluate_model(mobilenet_model, X_test_resized, y_test, "MobileNet")

results["CNN"] = evaluate_model(cnn_model, X_test, y_test, "CNN")
results["Proposed"] = evaluate_model(fusion_model, X_test, y_test, "Proposed Model")

# If you have saved models:
# from tensorflow.keras.models import load_model
# resnet_model = load_model("resnet.h5")
# efficient_model = load_model("efficientnet.h5")
# mobilenet_model = load_model("mobilenet.h5")

import pandas as pd

df = pd.DataFrame([
    [model, acc, prec, rec, f1]
    for model, (acc, prec, rec, f1) in results.items()
], columns=["Model", "Accuracy", "Precision", "Recall", "F1-score"])

print(df)

import matplotlib.pyplot as plt
import seaborn as sns

# Create a bar chart for Accuracy comparison
plt.figure(figsize=(10, 6))
sns.barplot(x='Model', y='Accuracy', data=df, palette='viridis')
plt.title('Model Accuracy Comparison', fontsize=16)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.ylim(0.8, 1.0) # Set y-axis limits to focus on the differences
plt.xticks(rotation=45, ha='right')

# Add accuracy values on top of the bars
for index, row in df.iterrows():
    plt.text(index, row.Accuracy + 0.005, f'{row.Accuracy:.4f}', color='black', ha='center')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Re-evaluating all models to ensure the results dictionary is populated
# The `results` dictionary was reset in cell 6fd23cf3 and should be populated by subsequent evaluation cells.
# This block ensures all model evaluations are recorded before creating the DataFrame.

results["ResNet50"] = evaluate_model(resnet_model, X_test_resized, y_test, "ResNet50")
results["EfficientNet"] = evaluate_model(efficient_model, X_test_resized, y_test, "EfficientNet")
results["MobileNet"] = evaluate_model(mobilenet_model, X_test_resized, y_test, "MobileNet")
results["CNN"] = evaluate_model(cnn_model, X_test, y_test, "CNN")
results["Proposed"] = evaluate_model(fusion_model, X_test, y_test, "Proposed Model")

# Create and print the DataFrame with all populated results
import pandas as pd

df = pd.DataFrame([
    [model, acc, prec, rec, f1]
    for model, (acc, prec, rec, f1) in results.items()
], columns=["Model", "Accuracy", "Precision", "Recall", "F1-score"])

print(df)

import matplotlib.pyplot as plt
import seaborn as sns

# Create a bar chart for Accuracy comparison
plt.figure(figsize=(10, 6))
sns.barplot(x='Model', y='Accuracy', data=df, palette='viridis')
plt.title('Model Accuracy Comparison', fontsize=16)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.ylim(0.0, 1.0) # Set y-axis limits
plt.xticks(rotation=45, ha='right')

# Add accuracy values on top of the bars
for index, row in df.iterrows():
    plt.text(index, row.Accuracy + 0.005, f'{row.Accuracy:.4f}', color='black', ha='center')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Model Performance Comparison Table"""

import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score
import tensorflow as tf

# Define evaluate_model function within this cell to ensure self-containment
def evaluate_model(model, X_data, y_true_labels, name):
    # Handle fusion model's dual input
    if name == "Proposed Model":
        # Check if gf_test is available, otherwise provide an empty array or handle error
        if 'gf_test' in globals():
            y_pred_probs = model.predict([X_data, gf_test], verbose=0)
        else:
            print(f"Warning: gf_test not found for {name}. Skipping evaluation.")
            return (0, 0, 0, 0) # Return zeros for metrics
    else:
        y_pred_probs = model.predict(X_data, verbose=0)

    y_pred_classes = np.argmax(y_pred_probs, axis=1)

    # Ensure y_true_labels is in the correct format (1D array for scikit-learn metrics)
    if y_true_labels.ndim > 1 and y_true_labels.shape[1] > 1:
        y_true_labels_1d = np.argmax(y_true_labels, axis=1)
    else:
        y_true_labels_1d = y_true_labels

    acc = accuracy_score(y_true_labels_1d, y_pred_classes)
    precision = precision_score(y_true_labels_1d, y_pred_classes, average='weighted', zero_division=0)
    recall = recall_score(y_true_labels_1d, y_pred_classes, average='weighted', zero_division=0)
    f1 = f1_score(y_true_labels_1d, y_pred_classes, average='weighted', zero_division=0)

    return acc, precision, recall, f1

# Initialize results dictionary within this cell
results = {}

# Evaluate all models and populate results (checks for existence of models and data)
if 'resnet_model' in globals() and 'X_test_resized' in globals() and 'y_test' in globals():
    results["ResNet50"] = evaluate_model(resnet_model, X_test_resized, y_test, "ResNet50")
if 'efficient_model' in globals() and 'X_test_resized' in globals() and 'y_test' in globals():
    results["EfficientNet"] = evaluate_model(efficient_model, X_test_resized, y_test, "EfficientNet")
if 'mobilenet_model' in globals() and 'X_test_resized' in globals() and 'y_test' in globals():
    results["MobileNet"] = evaluate_model(mobilenet_model, X_test_resized, y_test, "MobileNet")
if 'cnn_model' in globals() and 'X_test' in globals() and 'y_test' in globals():
    results["CNN"] = evaluate_model(cnn_model, X_test, y_test, "CNN")
if 'fusion_model' in globals() and 'X_test' in globals() and 'y_test' in globals() and 'gf_test' in globals():
    results["Proposed"] = evaluate_model(fusion_model, X_test, y_test, "Proposed Model")

# Create df from the results dictionary
df = pd.DataFrame(
    [[model, acc, prec, rec, f1]
    for model, (acc, prec, rec, f1) in results.items()],
    columns=["Model", "Accuracy", "Precision", "Recall", "F1-score"]
)

print("Model Performance Summary:")
display(df)

"""### Model F1-Score Comparison Plot"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score
import tensorflow as tf

# Define evaluate_model function within this cell to ensure self-containment
def evaluate_model(model, X_data, y_true_labels, name):
    # Handle fusion model's dual input
    if name == "Proposed Model":
        # Check if gf_test is available, otherwise provide an empty array or handle error
        if 'gf_test' in globals():
            y_pred_probs = model.predict([X_data, gf_test], verbose=0)
        else:
            print(f"Warning: gf_test not found for {name}. Skipping evaluation.")
            return (0, 0, 0, 0) # Return zeros for metrics
    else:
        y_pred_probs = model.predict(X_data, verbose=0)

    y_pred_classes = np.argmax(y_pred_probs, axis=1)

    # Ensure y_true_labels is in the correct format (1D array for scikit-learn metrics)
    if y_true_labels.ndim > 1 and y_true_labels.shape[1] > 1:
        y_true_labels_1d = np.argmax(y_true_labels, axis=1)
    else:
        y_true_labels_1d = y_true_labels

    acc = accuracy_score(y_true_labels_1d, y_pred_classes)
    precision = precision_score(y_true_labels_1d, y_pred_classes, average='weighted', zero_division=0)
    recall = recall_score(y_true_labels_1d, y_pred_classes, average='weighted', zero_division=0)
    f1 = f1_score(y_true_labels_1d, y_pred_classes, average='weighted', zero_division=0)

    return acc, precision, recall, f1

# Initialize results dictionary within this cell
results = {}

# Evaluate all models and populate results (checks for existence of models and data)
if 'resnet_model' in globals() and 'X_test_resized' in globals() and 'y_test' in globals():
    results["ResNet50"] = evaluate_model(resnet_model, X_test_resized, y_test, "ResNet50")
if 'efficient_model' in globals() and 'X_test_resized' in globals() and 'y_test' in globals():
    results["EfficientNet"] = evaluate_model(efficient_model, X_test_resized, y_test, "EfficientNet")
if 'mobilenet_model' in globals() and 'X_test_resized' in globals() and 'y_test' in globals():
    results["MobileNet"] = evaluate_model(mobilenet_model, X_test_resized, y_test, "MobileNet")
if 'cnn_model' in globals() and 'X_test' in globals() and 'y_test' in globals():
    results["CNN"] = evaluate_model(cnn_model, X_test, y_test, "CNN")
if 'fusion_model' in globals() and 'X_test' in globals() and 'y_test' in globals() and 'gf_test' in globals():
    results["Proposed"] = evaluate_model(fusion_model, X_test, y_test, "Proposed Model")

# Create df from the results dictionary
df = pd.DataFrame(
    [[model, acc, prec, rec, f1]
    for model, (acc, prec, rec, f1) in results.items()],
    columns=["Model", "Accuracy", "Precision", "Recall", "F1-score"]
)

plt.figure(figsize=(10, 6))
sns.barplot(x='Model', y='F1-score', data=df, palette='viridis')
plt.title('Model F1-Score Comparison', fontsize=16)
plt.xlabel('Model', fontsize=12)
plt.ylabel('F1-score', fontsize=12)
plt.ylim(0.0, 1.0) # Set y-axis limits
plt.xticks(rotation=45, ha='right')

# Add F1-score values on top of the bars
for index, row in df.iterrows():
    plt.text(index, row['F1-score'] + 0.005, f'{row['F1-score']:.4f}', color='black', ha='center')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import pandas as pd

# Assuming cm2 (confusion matrix for Fusion model) and CLASS_NAMES are available from previous execution
cm2_df = pd.DataFrame(cm2, index=CLASS_NAMES, columns=CLASS_NAMES)
cm2_df.index.name = 'True Label'
cm2_df.columns.name = 'Predicted Label'

print("Confusion Matrix for Fusion Model:")
display(cm2_df)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))
sns.heatmap(cm2_df, annot=True, fmt='d', cmap='Blues', cbar=False,
            linewidths=0.5, linecolor='black')
plt.title('Confusion Matrix Heatmap (Fusion Model)', fontsize=16)
plt.xlabel('Predicted Label', fontsize=12)
plt.ylabel('True Label', fontsize=12)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10, rotation=0)
plt.show()

from sklearn.metrics import classification_report

print('\n📋 Classification Report for Proposed (Fusion) Model:')
print(classification_report(y_true, y_fus_pred, target_names=CLASS_NAMES, digits=4))

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Calculate ROC curve and AUC for the Fusion model
fpr, tpr, thresholds = roc_curve(y_true, y_fus_prob[:, 1])
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='purple', lw=2, label=f'Fusion Model (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - Fusion Model', fontsize=14)
plt.legend(loc="lower right")
plt.grid(True)
plt.show()