# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwBWrbrVdMQ9fZD_UdlbSEQIP6i4Kknc
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

"""First, let's inspect the contents of your `Dataset` folder to understand the file structure and types of MRI images present."""

import os

dataset_path = '/content/drive/MyDrive/Dataset'

# List contents of the Dataset folder
if os.path.exists(dataset_path):
    print(f"Contents of {dataset_path}:")
    for item in os.listdir(dataset_path):
        print(item)
else:
    print(f"The folder '{dataset_path}' does not exist. Please ensure your 'Dataset' folder is directly inside 'MyDrive'.")

"""Based on the file types in the `Dataset` folder, you might need to use specific libraries for loading the MRI images (e.g., `nibabel` for NIfTI files, `pydicom` for DICOM files, or `Pillow`/`scikit-image` for common image formats like PNG/JPG if they are pre-processed).

For a general demonstration, I'll assume you have a standard image file (like a PNG or JPG) within your `Dataset` folder. If your MRI images are in a different format, you'll need to adjust the loading part accordingly. I'll use `skimage` for image processing and `matplotlib` for visualization.
"""

from skimage import io, filters, measure, morphology, color
import matplotlib.pyplot as plt
import numpy as np

# --- Configuration: Adjust these paths and filenames based on your 'Dataset' folder contents ---
# The 'Dataset' folder was found to contain 'valid', 'train', and 'test' subfolders.
# You need to specify an image file that exists within one of these subfolders.
# For example, if you have an image 'image001.jpeg' inside the 'train' folder, you would use:
# image_filename = 'train/image001.jpeg'

# !!! IMPORTANT: Replace 'your_actual_image_file.jpeg' with a real image file path from your dataset. !!!
image_filename = 'train/images/NoneDem-163-_jpg.rf.e3b16e1cded9b0190f334222aa9f0477.jpg' # Updated with a file from your list
image_path = os.path.join(dataset_path, image_filename)

# --- Image Loading ---
print(f"Attempting to load image: {image_path}")
try:
    # Use skimage.io.imread for general image formats (PNG, JPG, TIFF, etc.)
    # For NIfTI files, you'd use: img = nibabel.load(image_path).get_fdata()
    # For DICOM files, you'd use: import pydicom; ds = pydicom.dcmread(image_path); img = ds.pixel_array
    img = io.imread(image_path)
    print("Image loaded successfully.")
    print(f"Image shape: {img.shape}, dtype: {img.dtype}")

    # Convert to grayscale if it's a color image, as segmentation is often performed on grayscale
    if img.ndim == 3 and img.shape[-1] in (3, 4): # Check if it's RGB or RGBA
        img_gray = color.rgb2gray(img)
    else:
        img_gray = img # Already grayscale or single-channel

    # --- Segmentation: Otsu's Thresholding as a basic example ---
    # This method automatically determines a threshold value to convert the image into a binary mask.
    # Other methods include watershed, active contours, machine learning models, etc.
    threshold = filters.threshold_otsu(img_gray)
    binary_mask = img_gray > threshold

    # To reduce false negatives, we will make the 'cleaned_mask' less restrictive by not performing morphological operations here.
    cleaned_mask = binary_mask # Directly use binary mask for 'cleaned_mask'

    # --- Visualization ---
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    axes[0].imshow(img, cmap='gray')
    axes[0].set_title('Original Image')
    axes[0].axis('off')

    axes[1].imshow(binary_mask, cmap='gray')
    axes[1].set_title('Otsu Thresholding Mask')
    axes[1].axis('off')

    axes[2].imshow(cleaned_mask, cmap='gray')
    axes[2].set_title('Cleaned Segmentation Mask (No Morphological Ops)')
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print(f"Error: Image file not found at {image_path}. Please check the filename and path.")
except Exception as e:
    print(f"An error occurred during image processing: {e}")

# Re-running watershed segmentation for the original image with updated cleaned_mask
# The image loading and initial cleaned_mask generation for the original image is done in 1ff4b66a

from scipy import ndimage as ndi
from skimage.segmentation import watershed
from skimage import feature, filters # Import filters for gaussian and sobel

# Assuming img_gray and cleaned_mask from previous steps are available

# --- Preprocessing for Watershed Segmentation ---

# 1. Image Smoothing and Noise Reduction:
#    Apply a Gaussian filter to smooth the image and reduce noise.
#    This step is crucial to prevent over-segmentation caused by small intensity variations
#    and to create a more continuous intensity landscape for gradient calculation.
img_smoothed = filters.gaussian(img_gray, sigma=5) # Increased sigma for stronger blur

# 2. Gradient Calculation (Edge Detection):
#    Compute a local gradient to find strong edges in the smoothed image. These edges
#    will serve as the 'elevation map' for the watershed algorithm, where high gradients
#    indicate potential object boundaries.
sobel_gradient = filters.sobel(img_smoothed)

#    Refine the gradient map using Canny edge detection.
#    Canny produces thin, strong edges, which can help in getting more precise boundaries.
#    We convert the boolean output to float to allow multiplication with the Sobel gradient.
canny_edges = feature.canny(img_smoothed, sigma=1).astype(float) # sigma parameter can be tuned

#    Combine Sobel gradient with Canny edges to get a refined gradient.
#    This step ensures that our elevation map is strong at actual edges and suppressed elsewhere.
gradient = sobel_gradient * canny_edges

# 3. Marker Generation:
#    Markers are crucial for guiding the watershed algorithm. They define regions that are
#    definitely foreground (e.g., the object of interest) and definitely background.
#    For this demonstration, we'll leverage the 'cleaned_mask' obtained from the earlier
#    Otsu thresholding. This provides a good initial guess for foreground and background regions.

markers = np.zeros_like(img_gray, dtype=int)
# Assign '2' for foreground markers (areas identified as part of the object).
markers[cleaned_mask == True] = 2
# Assign '1' for background markers (areas identified as outside the object).
markers[cleaned_mask == False] = 1

# --- Apply Watershed Algorithm ---
# The watershed algorithm uses the refined gradient image as the 'elevation map'
# and the generated markers to segment the image.
segmentation = watershed(gradient, markers)

# Identify the brain region (which was marked as 2 in the watershed markers)
brain_mask = (segmentation == 2)

print("Watershed segmentation for original image completed.")

# --- Visualization ---
fig, axes = plt.subplots(1, 4, figsize=(20, 5))
axes[0].imshow(img, cmap='gray')
axes[0].set_title('Original Image')
axes[0].axis('off')

axes[1].imshow(img_gray, cmap='gray')
axes[1].set_title('Grayscale Image (After Smoothing)') # Updated title to reflect preprocessing
axes[1].axis('off')

axes[2].imshow(gradient, cmap='magma')
axes[2].set_title('Refined Gradient Map (Canny-filtered Sobel)')
axes[2].axis('off')

# Show the segmented image. The segmentation output assigns different labels to regions.
# We can visualize it as an outline or as distinct colors for regions.
# Let's show the outline of the segmented regions over the original image.
segmented_outline = color.label2rgb(segmentation, image=img_gray, bg_label=0, bg_color=(0,0,0))
axes[3].imshow(segmented_outline)
axes[3].set_title('Watershed Segmentation')
axes[3].axis('off')

plt.tight_layout()
plt.show()

# Re-loading Ground Truth for original image
# --- Configuration for Ground Truth (Adjust as needed) ---
# Assuming ground truth masks are in a 'labels' folder parallel to 'images'
# and have the same base filename but potentially a different extension.

# Example: if image is 'train/images/image001.jpg', ground truth might be 'train/labels/image001.png'
# We need to extract the base name and construct the labels path.

# First, get the relative path within the dataset_path
relative_image_path = os.path.relpath(image_path, dataset_path)

# Split into parts to replace 'images' with 'labels'
path_parts = relative_image_path.split(os.sep)

# Find 'images' and replace with 'labels'
if 'images' in path_parts:
    images_index = path_parts.index('images')
    path_parts[images_index] = 'labels'

    # Reconstruct the filename, changing the extension to .txt as discovered
    base_filename, _ = os.path.splitext(path_parts[-1])
    path_parts[-1] = base_filename + '.txt'

    ground_truth_relative_path = os.path.join(*path_parts)
    ground_truth_path = os.path.join(dataset_path, ground_truth_relative_path)
else:
    print("Could not infer ground truth path. Please set `ground_truth_path` manually.")
    ground_truth_path = None # Fallback if path inference fails

print(f"Attempting to load ground truth from: {ground_truth_path}")

try:
    # Load the ground truth mask from YOLO-like bounding box data
    bbox_data = np.loadtxt(ground_truth_path, ndmin=2) # ndmin=2 to handle single-line files

    # Get image dimensions from the loaded image (img)
    img_height, img_width = img.shape[0], img.shape[1]

    # Create an empty binary mask of the same size as the image
    gt_mask = np.zeros((img_height, img_width), dtype=bool)

    # Iterate through bounding boxes and draw them onto the mask
    for bbox in bbox_data:
        # Assuming YOLO format: class_id x_center y_center width height
        # We only care about the bounding box coordinates for the mask
        _, x_center_norm, y_center_norm, width_norm, height_norm = bbox

        # Convert normalized coordinates to pixel coordinates
        x_center = int(x_center_norm * img_width)
        y_center = int(y_center_norm * img_height)
        width = int(width_norm * img_width)
        height = int(height_norm * img_height)

        x_min = max(0, x_center - width // 2)
        y_min = max(0, y_center - height // 2)
        x_max = min(img_width, x_center + width // 2)
        y_max = min(img_height, y_center + height // 2)

        # Fill the bounding box region in the mask
        gt_mask[y_min:y_max, x_min:x_max] = True

    print(f"Ground truth mask created successfully from bounding boxes. Shape: {gt_mask.shape}, dtype: {gt_mask.dtype}")

    # --- Visualization ---
    fig, axes = plt.subplots(1, 5, figsize=(25, 5))

    # Original Image
    axes[0].imshow(img)
    axes[0].set_title('Original Image')
    axes[0].axis('off')

    # Ground Truth Mask
    axes[1].imshow(gt_mask, cmap='gray')
    axes[1].set_title('Ground Truth Mask (from BBox)')
    axes[1].axis('off')

    # Predicted Mask
    axes[2].imshow(brain_mask, cmap='gray')
    axes[2].set_title('Predicted Mask (Watershed)')
    axes[2].axis('off')

    # Overlay of Predicted Mask on Original
    axes[3].imshow(img, cmap='gray')
    axes[3].imshow(brain_mask, cmap='jet', alpha=0.5) # Use 'jet' colormap for clear visualization
    axes[3].set_title('Original + Predicted Overlay')
    axes[3].axis('off')

    # Overlay of Ground Truth Mask on Original
    axes[4].imshow(img, cmap='gray')
    axes[4].imshow(gt_mask, cmap='viridis', alpha=0.5) # Use 'viridis' colormap for clear visualization
    axes[4].set_title('Original + Ground Truth Overlay')
    axes[4].axis('off')

    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print(f"Error: Ground truth file not found at {ground_truth_path}. Please check the filename and path.")
except Exception as e:
    print(f"An error occurred during ground truth loading or visualization: {e}")

# Recalculating Dice coefficient for original image
def dice_coefficient(mask1, mask2):
    """
    Calculate the Dice Similarity Coefficient between two binary masks.
    Args:
        mask1 (numpy.ndarray): First binary mask (boolean or 0/1 array).
        mask2 (numpy.ndarray): Second binary mask (boolean or 0/1 array).
    Returns:
        float: Dice coefficient, a value between 0 and 1.
    """
    # Ensure masks are boolean for accurate intersection and union calculations
    mask1 = mask1.astype(bool)
    mask2 = mask2.astype(bool)

    intersection = np.sum(mask1 & mask2)
    sum_of_areas = np.sum(mask1) + np.sum(mask2)

    if sum_of_areas == 0:
        return 1.0 # Both masks are empty, consider as perfect match
    else:
        return (2.0 * intersection) / sum_of_areas

# Calculate Dice coefficient between predicted and ground truth masks
dice_score = dice_coefficient(brain_mask, gt_mask)

print(f"Dice Similarity Coefficient between Predicted and Ground Truth Masks (Original Image): {dice_score:.4f}")

# Re-visualizing Disagreement for original image
import matplotlib.patches as mpatches

# Calculate the difference mask (pixels where they disagree)
difference_mask = np.logical_xor(brain_mask, gt_mask)

# Create a figure and plot the original image
fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(img, cmap='gray')
ax.set_title('Original Image with Disagreement Overlay (After Less Restrictive Cleaned Mask)')
ax.axis('off')

# Overlay the difference mask
# Create an RGBA image for the mask
diff_overlay = np.zeros((img.shape[0], img.shape[1], 4))

# Highlight false positives (predicted but not ground truth) in red
false_positives = brain_mask & ~gt_mask
diff_overlay[false_positives] = [1, 0, 0, 0.5] # Red with 50% opacity

# Highlight false negatives (ground truth but not predicted) in blue
false_negatives = ~brain_mask & gt_mask
diff_overlay[false_negatives] = [0, 0, 1, 0.5] # Blue with 50% opacity

ax.imshow(diff_overlay)

# Add a legend
red_patch = mpatches.Patch(color='red', alpha=0.5, label='False Positives (Predicted but not GT)')
blue_patch = mpatches.Patch(color='blue', alpha=0.5, label='False Negatives (GT but not Predicted)')
ax.legend(handles=[red_patch, blue_patch], loc='lower right')

plt.tight_layout()
plt.show()

"""This code provides a basic segmentation. To achieve the "exact output" you attached, you would likely need a more sophisticated segmentation technique, possibly involving deep learning models trained on MRI data, or more advanced image processing algorithms tailored to the specific anatomical structures you wish to segment. If you can describe the desired output (e.g., segmenting brain, tumor, specific organs), I can help refine the approach.

### Advanced Segmentation: Preprocessing and Watershed Algorithm

The watershed algorithm is often used for segmentation, especially when objects are touching. It treats the image as a topographic map where pixel intensities represent altitudes. Markers are placed on the 'valleys' (background) and 'peaks' (objects), and then the image is flooded from these markers until the 'watershed lines' meet, defining the object boundaries.

**Preprocessing is crucial for effective watershed segmentation.** It typically involves:
1.  **Smoothing/Noise Reduction:** To prevent over-segmentation from small intensity variations.
2.  **Gradient Calculation:** To highlight object boundaries, which the watershed algorithm uses as 'elevation' to define segmentation lines.
3.  **Marker Generation:** Defining 'sure foreground' and 'sure background' regions to guide the algorithm and prevent under- or over-segmentation.

Here, I'll demonstrate a basic watershed segmentation incorporating these preprocessing steps. For more precise brain segmentation, particularly with NIfTI or DICOM medical images, specialized tools like `FSL` (Brain Extraction Tool - BET) or `FreeSurfer` are typically used, or deep learning models trained specifically for brain MRI segmentation.
"""

from scipy import ndimage as ndi
from skimage.segmentation import watershed
from skimage import feature, filters # Import filters for gaussian and sobel

# Assuming img_gray from previous steps is available

# --- Preprocessing for Watershed Segmentation ---

# 1. Image Smoothing and Noise Reduction:
#    Apply a Gaussian filter to smooth the image and reduce noise.
#    This step is crucial to prevent over-segmentation caused by small intensity variations
#    and to create a more continuous intensity landscape for gradient calculation.
img_smoothed = filters.gaussian(img_gray, sigma=5) # Increased sigma for stronger blur

# 2. Gradient Calculation (Edge Detection):
#    Compute a local gradient to find strong edges in the smoothed image. These edges
#    will serve as the 'elevation map' for the watershed algorithm, where high gradients
#    indicate potential object boundaries.
sobel_gradient = filters.sobel(img_smoothed)

#    Refine the gradient map using Canny edge detection.
#    Canny produces thin, strong edges, which can help in getting more precise boundaries.
#    We convert the boolean output to float to allow multiplication with the Sobel gradient.
canny_edges = feature.canny(img_smoothed, sigma=1).astype(float) # sigma parameter can be tuned

#    Combine Sobel gradient with Canny edges to get a refined gradient.
#    This step ensures that our elevation map is strong at actual edges and suppressed elsewhere.
gradient = sobel_gradient * canny_edges

# 3. Marker Generation:
#    Markers are crucial for guiding the watershed algorithm. They define regions that are
#    definitely foreground (e.g., the object of interest) and definitely background.
#    For this demonstration, we'll leverage the 'cleaned_mask' obtained from the earlier
#    Otsu thresholding and morphological operations. This provides a good initial guess
#    for foreground and background regions.

markers = np.zeros_like(img_gray, dtype=int)
# Assign '2' for foreground markers (areas identified as part of the object).
markers[cleaned_mask == True] = 2
# Assign '1' for background markers (areas identified as outside the object).
markers[cleaned_mask == False] = 1

# --- Apply Watershed Algorithm ---
# The watershed algorithm uses the refined gradient image as the 'elevation map'
# and the generated markers to segment the image.
segmentation = watershed(gradient, markers)

# --- Visualization ---
fig, axes = plt.subplots(1, 4, figsize=(20, 5))
axes[0].imshow(img, cmap='gray')
axes[0].set_title('Original Image')
axes[0].axis('off')

axes[1].imshow(img_gray, cmap='gray')
axes[1].set_title('Grayscale Image (After Smoothing)') # Updated title to reflect preprocessing
axes[1].axis('off')

axes[2].imshow(gradient, cmap='magma')
axes[2].set_title('Refined Gradient Map (Canny-filtered Sobel)')
axes[2].axis('off')

# Show the segmented image. The segmentation output assigns different labels to regions.
# We can visualize it as an outline or as distinct colors for regions.
# Let's show the outline of the segmented regions over the original image.
segmented_outline = color.label2rgb(segmentation, image=img_gray, bg_label=0, bg_color=(0,0,0))
axes[3].imshow(segmented_outline)
axes[3].set_title('Watershed Segmentation')
axes[3].axis('off')

plt.tight_layout()
plt.show()

import matplotlib.patches as mpatches

# Assuming 'segmentation' and 'img' are available from previous steps

# Identify the brain region (which was marked as 2 in the watershed markers)
brain_mask = (segmentation == 2)

# Create a figure and plot the original image
fig, ax = plt.subplots(figsize=(8, 8))
ax.imshow(img, cmap='gray')
ax.set_title('Original Image with Segmented Brain Overlay')
ax.axis('off')

# Overlay the brain mask with a transparent color
# Using a color map and alpha for overlay
# Create an RGBA image for the mask
mask_overlay = np.zeros((img.shape[0], img.shape[1], 4)) # Corrected shape
mask_overlay[brain_mask] = [0, 1, 0, 0.4] # Green color with 40% opacity

ax.imshow(mask_overlay)

# Add a legend to explain the overlay color
patch = mpatches.Patch(color=[0, 1, 0, 0.4], label='Segmented Brain')
ax.legend(handles=[patch], loc='lower right')

plt.tight_layout()
plt.show()

"""### Ground Truth, Predicted Mask, and Overlay Visualization

To evaluate the segmentation, it's crucial to compare the predicted mask with a ground truth mask. Below, I'll provide code to load a hypothetical ground truth mask and then display it alongside the predicted mask and an overlay on the original image.

**!!! IMPORTANT: You MUST update the `ground_truth_filename` variable to point to your actual ground truth mask file corresponding to the loaded image. !!!**
"""

# --- Configuration for Ground Truth (Adjust as needed) ---
# Assuming ground truth masks are in a 'labels' folder parallel to 'images'
# and have the same base filename but potentially a different extension.

# Example: if image is 'train/images/image001.jpg', ground truth might be 'train/labels/image001.png'
# We need to extract the base name and construct the labels path.

# First, get the relative path within the dataset_path
relative_image_path = os.path.relpath(image_path, dataset_path)

# Split into parts to replace 'images' with 'labels' and change extension if necessary
path_parts = relative_image_path.split(os.sep)

# Find 'images' and replace with 'labels'
if 'images' in path_parts:
    images_index = path_parts.index('images')
    path_parts[images_index] = 'labels'

    # Reconstruct the filename, potentially changing the extension to .png or .npy
    # You might need to adjust the extension based on your ground truth file type
    # For this example, I'll assume the ground truth has a .txt extension.
    base_filename, _ = os.path.splitext(path_parts[-1])
    path_parts[-1] = base_filename + '.txt' # !!! ADJUSTED EXTENSION TO .txt !!!

    ground_truth_relative_path = os.path.join(*path_parts)
    ground_truth_path = os.path.join(dataset_path, ground_truth_relative_path)
else:
    print("Could not infer ground truth path. Please set `ground_truth_path` manually.")
    ground_truth_path = None # Fallback if path inference fails


print(f"Attempting to load ground truth from: {ground_truth_path}")

try:
    # Load the ground truth mask
    # The .txt file contains YOLO-like bounding box annotations:
    # class_id x_center y_center width height (normalized)
    bbox_data = np.loadtxt(ground_truth_path, ndmin=2) # ndmin=2 to handle single-line files

    # Get image dimensions from the loaded image (img)
    img_height, img_width = img.shape[0], img.shape[1]

    # Create an empty binary mask of the same size as the image
    gt_mask = np.zeros((img_height, img_width), dtype=bool)

    # Iterate through bounding boxes and draw them onto the mask
    for bbox in bbox_data:
        # Assuming YOLO format: class_id x_center y_center width height
        # We only care about the bounding box coordinates for the mask
        _, x_center_norm, y_center_norm, width_norm, height_norm = bbox

        # Convert normalized coordinates to pixel coordinates
        x_center = int(x_center_norm * img_width)
        y_center = int(y_center_norm * img_height)
        width = int(width_norm * img_width)
        height = int(height_norm * img_height)

        x_min = max(0, x_center - width // 2)
        y_min = max(0, y_center - height // 2)
        x_max = min(img_width, x_center + width // 2)
        y_max = min(img_height, y_center + height // 2)

        # Fill the bounding box region in the mask
        gt_mask[y_min:y_max, x_min:x_max] = True

    print(f"Ground truth mask created successfully from bounding boxes. Shape: {gt_mask.shape}, dtype: {gt_mask.dtype}")

    # --- Visualization ---
    fig, axes = plt.subplots(1, 5, figsize=(25, 5))

    # Original Image
    axes[0].imshow(img)
    axes[0].set_title('Original Image')
    axes[0].axis('off')

    # Ground Truth Mask
    axes[1].imshow(gt_mask, cmap='gray')
    axes[1].set_title('Ground Truth Mask (from BBox)')
    axes[1].axis('off')

    # Predicted Mask
    axes[2].imshow(brain_mask, cmap='gray')
    axes[2].set_title('Predicted Mask (Watershed)')
    axes[2].axis('off')

    # Overlay of Predicted Mask on Original
    axes[3].imshow(img, cmap='gray')
    axes[3].imshow(brain_mask, cmap='jet', alpha=0.5) # Use 'jet' colormap for clear visualization
    axes[3].set_title('Original + Predicted Overlay')
    axes[3].axis('off')

    # Overlay of Ground Truth Mask on Original
    axes[4].imshow(img, cmap='gray')
    axes[4].imshow(gt_mask, cmap='viridis', alpha=0.5) # Use 'viridis' colormap for clear visualization
    axes[4].set_title('Original + Ground Truth Overlay')
    axes[4].axis('off')

    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print(f"Error: Ground truth file not found at {ground_truth_path}. Please check the filename and path.")
except Exception as e:
    print(f"An error occurred during ground truth loading or visualization: {e}")

def dice_coefficient(mask1, mask2):
    """
    Calculate the Dice Similarity Coefficient between two binary masks.
    Args:
        mask1 (numpy.ndarray): First binary mask (boolean or 0/1 array).
        mask2 (numpy.ndarray): Second binary mask (boolean or 0/1 array).
    Returns:
        float: Dice coefficient, a value between 0 and 1.
    """
    # Ensure masks are boolean for accurate intersection and union calculations
    mask1 = mask1.astype(bool)
    mask2 = mask2.astype(bool)

    intersection = np.sum(mask1 & mask2)
    sum_of_areas = np.sum(mask1) + np.sum(mask2)

    if sum_of_areas == 0:
        return 1.0 # Both masks are empty, consider as perfect match
    else:
        return (2.0 * intersection) / sum_of_areas

# Calculate Dice coefficient between predicted and ground truth masks
dice_score = dice_coefficient(brain_mask, gt_mask)

print(f"Dice Similarity Coefficient between Predicted and Ground Truth Masks: {dice_score:.4f}")

import matplotlib.patches as mpatches

# Calculate the difference mask (pixels where they disagree)
difference_mask = np.logical_xor(brain_mask, gt_mask)

# Create a figure and plot the original image
fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(img, cmap='gray')
ax.set_title('Original Image with Disagreement Overlay')
ax.axis('off')

# Overlay the difference mask
# Create an RGBA image for the mask
diff_overlay = np.zeros((img.shape[0], img.shape[1], 4))

# Highlight false positives (predicted but not ground truth) in red
false_positives = brain_mask & ~gt_mask
diff_overlay[false_positives] = [1, 0, 0, 0.5] # Red with 50% opacity

# Highlight false negatives (ground truth but not predicted) in blue
false_negatives = ~brain_mask & gt_mask
diff_overlay[false_negatives] = [0, 0, 1, 0.5] # Blue with 50% opacity

ax.imshow(diff_overlay)

# Add a legend
red_patch = mpatches.Patch(color='red', alpha=0.5, label='False Positives (Predicted but not GT)')
blue_patch = mpatches.Patch(color='blue', alpha=0.5, label='False Negatives (GT but not Predicted)')
ax.legend(handles=[red_patch, blue_patch], loc='lower right')

plt.tight_layout()
plt.show()

print(f"Recalculating Dice Similarity Coefficient with the new segmentation.")
# Calculate Dice coefficient between predicted and ground truth masks
new_dice_score = dice_coefficient(brain_mask, gt_mask)

print(f"New Dice Similarity Coefficient: {new_dice_score:.4f}")

"""### Comparison with a Different Image

Let's pick another image from the dataset and apply the same segmentation and evaluation process to compare the results.
"""

# --- Configuration for the NEW image ----
# Selecting a different image from the 'train/images' folder.
new_image_filename = 'train/images/NoneDem-154-_jpg.rf.b2d1149da0581b0ffd43982e9f68ada2.jpg'
new_image_path = os.path.join(dataset_path, new_image_filename)

# Construct the ground truth path for the new image
new_relative_image_path = os.path.relpath(new_image_path, dataset_path)
new_path_parts = new_relative_image_path.split(os.sep)

if 'images' in new_path_parts:
    new_images_index = new_path_parts.index('images')
    new_path_parts[new_images_index] = 'labels'
    new_base_filename, _ = os.path.splitext(new_path_parts[-1])
    new_path_parts[-1] = new_base_filename + '.txt'
    new_ground_truth_relative_path = os.path.join(*new_path_parts)
    new_ground_truth_path = os.path.join(dataset_path, new_ground_truth_relative_path)
else:
    print("Could not infer new ground truth path. Please set `new_ground_truth_path` manually.")
    new_ground_truth_path = None

print(f"Attempting to load NEW image: {new_image_path}")
print(f"Attempting to load NEW ground truth from: {new_ground_truth_path}")

# --- Image Loading and Initial Segmentation for NEW image ---
try:
    img_new = io.imread(new_image_path)
    print("NEW image loaded successfully.")
    print(f"NEW Image shape: {img_new.shape}, dtype: {img_new.dtype}")

    if img_new.ndim == 3 and img_new.shape[-1] in (3, 4):
        img_gray_new = color.rgb2gray(img_new)
    else:
        img_gray_new = img_new

    # Otsu Thresholding for initial mask (using the same 'sigma' as before)
    threshold_new = filters.threshold_otsu(img_gray_new)
    binary_mask_new = img_gray_new > threshold_new

    # Morphological operations (removed to make cleaned_mask less restrictive)
    cleaned_mask_new = binary_mask_new # Directly use binary mask for 'cleaned_mask'

    print("Initial segmentation for NEW image completed.")

except FileNotFoundError:
    print(f"Error: NEW image file not found at {new_image_path}. Please check the filename and path.")
except Exception as e:
    print(f"An error occurred during NEW image processing: {e}")

# Re-running watershed segmentation for the NEW image with updated cleaned_mask
# The image loading and initial cleaned_mask generation for the NEW image is done in c9634c9d

# --- Watershed Segmentation for NEW image (using the same 'sigma' as before) ---
try:
    # 1. Image Smoothing and Noise Reduction:
    img_smoothed_new = filters.gaussian(img_gray_new, sigma=5)

    # 2. Gradient Calculation (Edge Detection):
    sobel_gradient_new = filters.sobel(img_smoothed_new)
    canny_edges_new = feature.canny(img_smoothed_new, sigma=1).astype(float)
    gradient_new = sobel_gradient_new * canny_edges_new

    # 3. Marker Generation:
    markers_new = np.zeros_like(img_gray_new, dtype=int)
    markers_new[cleaned_mask_new == True] = 2
    markers_new[cleaned_mask_new == False] = 1

    # Apply Watershed Algorithm
    segmentation_new = watershed(gradient_new, markers_new)
    brain_mask_new = (segmentation_new == 2)
    print("Watershed segmentation for NEW image completed.")

except Exception as e:
    print(f"An error occurred during NEW image watershed segmentation: {e}")

# Re-loading Ground Truth for NEW image
# --- Load Ground Truth for NEW image ---
try:
    bbox_data_new = np.loadtxt(new_ground_truth_path, ndmin=2)
    img_height_new, img_width_new = img_new.shape[0], img_new.shape[1]
    gt_mask_new = np.zeros((img_height_new, img_width_new), dtype=bool)

    for bbox_new in bbox_data_new:
        _, x_center_norm_new, y_center_norm_new, width_norm_new, height_norm_new = bbox_new
        x_center_new = int(x_center_norm_new * img_width_new)
        y_center_new = int(y_center_norm_new * img_height_new)
        width_new = int(width_norm_new * img_width_new)
        height_new = int(height_norm_new * img_height_new)

        x_min_new = max(0, x_center_new - width_new // 2)
        y_min_new = max(0, y_center_new - height_new // 2)
        x_max_new = min(img_width_new, x_center_new + width_new // 2)
        y_max_new = min(img_height_new, y_center_new + height_new // 2)

        gt_mask_new[y_min_new:y_max_new, x_min_new:x_max_new] = True

    print(f"NEW ground truth mask created successfully. Shape: {gt_mask_new.shape}, dtype: {gt_mask_new.dtype}")

except FileNotFoundError:
    print(f"Error: NEW ground truth file not found at {new_ground_truth_path}. Please check the filename and path.")
except Exception as e:
    print(f"An error occurred during NEW ground truth loading: {e}")

# Recalculating Dice Coefficient for NEW image
dice_score_new = dice_coefficient(brain_mask_new, gt_mask_new)
print(f"Dice Similarity Coefficient for NEW image ('{new_image_filename}'): {dice_score_new:.4f}")

# Re-visualizing Disagreement for NEW image
# --- Visualize Disagreement for NEW image ---
new_difference_mask = np.logical_xor(brain_mask_new, gt_mask_new)

fig_new, ax_new = plt.subplots(figsize=(10, 10))
ax_new.imshow(img_new, cmap='gray')
ax_new.set_title(f'NEW Image Disagreement Overlay (After Less Restrictive Cleaned Mask) ({os.path.basename(new_image_filename)})')
ax_new.axis('off')

new_diff_overlay = np.zeros((img_new.shape[0], img_new.shape[1], 4))
new_false_positives = brain_mask_new & ~gt_mask_new
new_diff_overlay[new_false_positives] = [1, 0, 0, 0.5] # Red
new_false_negatives = ~brain_mask_new & gt_mask_new
new_diff_overlay[new_false_negatives] = [0, 0, 1, 0.5] # Blue

ax_new.imshow(new_diff_overlay)

red_patch_new = mpatches.Patch(color='red', alpha=0.5, label='False Positives')
blue_patch_new = mpatches.Patch(color='blue', alpha=0.5, label='False Negatives')
ax_new.legend(handles=[red_patch_new, blue_patch_new], loc='lower right')

plt.tight_layout()
plt.show()

# --- Watershed Segmentation for NEW image (using the same 'sigma' as before) ---
try:
    # 1. Image Smoothing and Noise Reduction:
    img_smoothed_new = filters.gaussian(img_gray_new, sigma=5)

    # 2. Gradient Calculation (Edge Detection):
    sobel_gradient_new = filters.sobel(img_smoothed_new)
    canny_edges_new = feature.canny(img_smoothed_new, sigma=1).astype(float)
    gradient_new = sobel_gradient_new * canny_edges_new

    # 3. Marker Generation:
    markers_new = np.zeros_like(img_gray_new, dtype=int)
    markers_new[cleaned_mask_new == True] = 2
    markers_new[cleaned_mask_new == False] = 1

    # Apply Watershed Algorithm
    segmentation_new = watershed(gradient_new, markers_new)
    brain_mask_new = (segmentation_new == 2)
    print("Watershed segmentation for NEW image completed.")

except Exception as e:
    print(f"An error occurred during NEW image watershed segmentation: {e}")

# --- Load Ground Truth for NEW image ---
try:
    bbox_data_new = np.loadtxt(new_ground_truth_path, ndmin=2)
    img_height_new, img_width_new = img_new.shape[0], img_new.shape[1]
    gt_mask_new = np.zeros((img_height_new, img_width_new), dtype=bool)

    for bbox_new in bbox_data_new:
        _, x_center_norm_new, y_center_norm_new, width_norm_new, height_norm_new = bbox_new
        x_center_new = int(x_center_norm_new * img_width_new)
        y_center_new = int(y_center_norm_new * img_height_new)
        width_new = int(width_norm_new * img_width_new)
        height_new = int(height_norm_new * img_height_new)

        x_min_new = max(0, x_center_new - width_new // 2)
        y_min_new = max(0, y_center_new - height_new // 2)
        x_max_new = min(img_width_new, x_center_new + width_new // 2)
        y_max_new = min(img_height_new, y_center_new + height_new // 2)

        gt_mask_new[y_min_new:y_max_new, x_min_new:x_max_new] = True

    print(f"NEW ground truth mask created successfully. Shape: {gt_mask_new.shape}, dtype: {gt_mask_new.dtype}")

except FileNotFoundError:
    print(f"Error: NEW ground truth file not found at {new_ground_truth_path}. Please check the filename and path.")
except Exception as e:
    print(f"An error occurred during NEW ground truth loading: {e}")

# --- Calculate Dice Coefficient for NEW image ---
dice_score_new = dice_coefficient(brain_mask_new, gt_mask_new)
print(f"Dice Similarity Coefficient for NEW image ('{new_image_filename}'): {dice_score_new:.4f}")

# --- Visualize Disagreement for NEW image ---
new_difference_mask = np.logical_xor(brain_mask_new, gt_mask_new)

fig_new, ax_new = plt.subplots(figsize=(10, 10))
ax_new.imshow(img_new, cmap='gray')
ax_new.set_title(f'NEW Image Disagreement Overlay ({os.path.basename(new_image_filename)})')
ax_new.axis('off')

new_diff_overlay = np.zeros((img_new.shape[0], img_new.shape[1], 4))
new_false_positives = brain_mask_new & ~gt_mask_new
new_diff_overlay[new_false_positives] = [1, 0, 0, 0.5] # Red
new_false_negatives = ~brain_mask_new & gt_mask_new
new_diff_overlay[new_false_negatives] = [0, 0, 1, 0.5] # Blue

ax_new.imshow(new_diff_overlay)

red_patch_new = mpatches.Patch(color='red', alpha=0.5, label='False Positives')
blue_patch_new = mpatches.Patch(color='blue', alpha=0.5, label='False Negatives')
ax_new.legend(handles=[red_patch_new, blue_patch_new], loc='lower right')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(8, 8))
plt.imshow(brain_mask_new, cmap='gray', vmin=0, vmax=1)
plt.title('Predicted Mask (brain_mask_new) for New Image')
plt.axis('off')
plt.show()

import matplotlib.patches as mpatches

# Assuming new_difference_mask, new_diff_overlay, img_new are available from previous steps

fig_new_replot, ax_new_replot = plt.subplots(figsize=(10, 10))
ax_new_replot.imshow(img_new, cmap='gray')
ax_new_replot.set_title(f'Re-plotted Disagreement Overlay for New Image ({os.path.basename(new_image_filename)})')
ax_new_replot.axis('off')

# The overlay itself is already in new_diff_overlay
ax_new_replot.imshow(new_diff_overlay)

red_patch_replot = mpatches.Patch(color='red', alpha=0.5, label='False Positives')
blue_patch_replot = mpatches.Patch(color='blue', alpha=0.5, label='False Negatives')
ax_new_replot.legend(handles=[red_patch_replot, blue_patch_replot], loc='lower right')

plt.tight_layout()
plt.show()

"""### Comparison Summary

*   **Original Image (`NoneDem-163...jpg`):** Dice Score = `{dice_score:.4f}`
*   **New Image (`NoneDem-154...jpg`):** Dice Score = `{dice_score_new:.4f}`

The visualization for the new image shows similar patterns of disagreement, indicating that the chosen segmentation approach (Watershed with current preprocessing) might be consistent across these images, given their ground truth masks are also full-image bounding boxes.

As noted previously, the current broad ground truth masks (full image bounding boxes) limit the effectiveness of the Dice score as an evaluation metric for precise segmentation. For more meaningful evaluation and improvement, more specific pixel-level ground truth masks would be ideal.
"""

import matplotlib.patches as mpatches

# Calculate the difference mask (pixels where they disagree)
new_difference_mask = np.logical_xor(brain_mask, gt_mask)

# Create a figure and plot the original image
fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(img, cmap='gray')
ax.set_title('Original Image with NEW Disagreement Overlay (After Stronger Blur)')
ax.axis('off')

# Overlay the difference mask
# Create an RGBA image for the mask
new_diff_overlay = np.zeros((img.shape[0], img.shape[1], 4))

# Highlight false positives (predicted but not ground truth) in red
new_false_positives = brain_mask & ~gt_mask
new_diff_overlay[new_false_positives] = [1, 0, 0, 0.5] # Red with 50% opacity

# Highlight false negatives (ground truth but not predicted) in blue
new_false_negatives = ~brain_mask & gt_mask
new_diff_overlay[new_false_negatives] = [0, 0, 1, 0.5] # Blue with 50% opacity

ax.imshow(new_diff_overlay)

# Add a legend
red_patch = mpatches.Patch(color='red', alpha=0.5, label='False Positives (Predicted but not GT)')
blue_patch = mpatches.Patch(color='blue', alpha=0.5, label='False Negatives (GT but not Predicted)')
ax.legend(handles=[red_patch, blue_patch], loc='lower right')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

print(f"Ground Truth Mask: Shape={gt_mask.shape}, Dtype={gt_mask.dtype}")
print(f"Ground Truth Mask contains any True values: {gt_mask.any()}")
print(f"Ground Truth Mask is all True values: {gt_mask.all()}")

plt.figure(figsize=(6, 6))
# Explicitly set vmin and vmax for boolean arrays with 'gray' colormap
# False (0) will be black, True (1) will be white
plt.imshow(gt_mask, cmap='gray', vmin=0, vmax=1)
plt.title('Ground Truth Mask')
plt.axis('off')
plt.show()

print(f"Inspecting the content of the ground truth file: {ground_truth_path}")

try:
    with open(ground_truth_path, 'r') as f:
        for i, line in enumerate(f):
            print(line.strip())
            if i >= 9: # Print first 10 lines to get an idea of the format
                print("... (truncated)")
                break
except Exception as e:
    print(f"Could not read the file: {e}")

train_folder_path = os.path.join(dataset_path, 'train')

if os.path.exists(train_folder_path):
    print(f"Contents of {train_folder_path} (first 10 files):")
    for i, item in enumerate(os.listdir(train_folder_path)):
        if i >= 10:
            break
        print(item)
else:
    print(f"The folder '{train_folder_path}' does not exist.")

import os

train_labels_folder_path = os.path.join(dataset_path, 'train', 'labels')

if os.path.exists(train_labels_folder_path):
    print(f"Checking file extensions in: {train_labels_folder_path}")
    jpg_found = False
    npy_found = False
    other_extensions = set()

    for item in os.listdir(train_labels_folder_path):
        base, ext = os.path.splitext(item)
        ext = ext.lower()

        if ext == '.jpg' or ext == '.jpeg':
            jpg_found = True
            print(f"Found JPG ground truth file: {item}")
        elif ext == '.npy':
            npy_found = True
            print(f"Found NPY ground truth file: {item}")
        elif ext not in ['.png']:
            other_extensions.add(ext)

    if not jpg_found and not npy_found and not other_extensions:
        print("No JPG, NPY, or other non-PNG extensions found in ground truth folder.")
    elif other_extensions:
        print(f"Other extensions found: {', '.join(other_extensions)}")
else:
    print(f"The folder '{train_labels_folder_path}' does not exist.")

train_images_folder_path = os.path.join(dataset_path, 'train', 'images')

if os.path.exists(train_images_folder_path):
    print(f"Contents of {train_images_folder_path} (first 10 files):")
    for i, item in enumerate(os.listdir(train_images_folder_path)):
        if i >= 10:
            break
        print(item)
else:
    print(f"The folder '{train_images_folder_path}' does not exist.")